### ISSUE TITLE
【ModelArts Explore】多种方法，将猫狗识别率调试到95%以上

### ISSUE THREAD

**Issue by yiakwy** [huaweicloud/ModelArts-Lab#131]
详细情况见笔记：https://github.com/yiakwy/SpatialPerceptron/blob/master/notebooks/ModelArts-Explore_ex1.ipynb

**Comment by chenliang613** [comment]
感谢分享！

**Comment by chaoxu1203** [comment]
你好，我看了一下这个分享笔记，觉得内容很丰富，很好。现在我们邀请你将猫狗识别图像分类的高精度notebook代码（带运行结果，将案例无关的信息精简一下）贡献到我们社区，我们会给你额外的积分奖励。
贡献路径：contrib路径下，在contrib路径下新建一个文件夹，名称为 “猫狗识别图像分类案例-<你的github账号名称>“，将notebook ipynb文件和相关文件放入文件夹下即可。谢谢。

**Comment by containerteam** [comment]
在notebook 中使用MaskRCNN 这种实例分隔模型对性能损失有点太大了。建议只使用MaskRCNN的主干网络(ResNet + FPN)再加个分类器 比较合适。

**Comment by yiakwy** [comment]
@containerteam 收到哈，谢谢宝贵的建议！
@chaoxu1203 已经在做了，带上了部署到华为云的一些代码，适合在命令行模式下通过集群运行
@chenliang613 谢谢啦！

**Comment by Melaniemod** [comment]
已经404了

**Comment by yiakwy** [comment]
@Melaniemod 您好已经合并到主分支中的Samples里面。如果您想看原先的实现可以在repo 中开放的Notebook中寻找，去年很久以前就已经更名了。

@chenliang613 因为这个问题以及解决了，因此关闭这个问题。
