### ISSUE TITLE
【华为云 ModelArts-Lab AI实战营】第十三期：人脸系列（III）表情检测

### ISSUE THREAD

**Issue by sunbo57123** [huaweicloud/ModelArts-Lab#1343]
# 【华为云 ModelArts-Lab AI实战营】第十三期

- 相信访问本页面的您，已经是《华为云 ModelArts-Lab AI实战营》前十二期的的学员，并且已经熟悉ModelArts平台的基本操作了。本期已经是人脸系列的第三期内容了，这次我们完成人脸表情识别的任务。

- **本期实战，会涉及少量存储费用，请保证账户余额至少1元参与本期活动，请见[费用 FAQ 说明](https://github.com/huaweicloud/ModelArts-Lab/blob/master/docs/faqs.md)。**

## 本期实战营参与说明

> 本期实战为人脸系列第三期，我们通过构建深度学习网络对人脸表情数据集进行识别。将不同的情绪视作不同的分类，构建卷积神经网络完成分类任务。数据预处理部分通过MTCNN完成人脸的检测任务。

1. 【本期实战内容】
  - 第十三期案例：[表情判断案例](https://github.com/huaweicloud/ModelArts-Lab/tree/master/notebook/DL_face_facial_expression)

2. 【加入实战微信群】
  - 欢迎您自由加入本期实战营的微信群，与 ModelArts 社区开发者一起交流
  - 请添加 “华为云 EI 微信小助手” 后，拉您入群（微信号：huaweisecretary）

3. 【留下实战记录】
  - 请在本 Issue 下方跟帖反馈：<b>华为云账号 + 完成截图</b>。[点击跟帖反馈本期实战截图](https://github.com/huaweicloud/ModelArts-Lab/issues/1343#new_comment_field)
  - 反馈信息格式，请参考如下 @SUNNYDAYY  的样例

4. 【本期积分规则】
    - <b>本期实战需要反馈2个截图，获得1个积分，虽然可以使用我们提供的图片，但建议大家自己上传自定义图片</b>：
            - <b>人脸检测结果</b>
            - <b>表情判断结果</b>
    - <b>注意，请在截图中体现出个人标识</b>

    - 本期实战获得额外积分的方式包括但不限于：
    对网络进行优化，进行数据增广等，更多的调优方式参考第三期内容，贡献文章和拓展案例请参照[contrib](https://github.com/huaweicloud/ModelArts-Lab/tree/master/contrib)。获取额外积分结果将由社区 committer 共同讨论商定。

5. 【手动停止服务】
  - 实验完成后，请**手动停止**占用云资源的服务，如：停止 “开发环境” 中所创建的 Notebook 以及 “部署上线”-“在线服务” 中所部署的在线服务，以避免因持续占用云资源导致资源包无谓消耗和欠费发生。需使用时，再启动即可。

6. 【获得实践积分】
  - 完成实战记录并回帖的开发者，请提交 Pull Request (PR) 到 [积分总表](https://github.com/huaweicloud/ModelArts-Lab/blob/master/merit_rank/all_ranking.md)，反馈您的实践、积分和贡献点，[具体操作流程在此](https://github.com/huaweicloud/ModelArts-Lab/wiki/Pull-Requests-%E6%9B%B4%E6%96%B0%E7%A7%AF%E5%88%86)。社区 Committers 核实后，合并 PR，积分正式生效。
  - 积分规则： [https://github.com/huaweicloud/ModelArts-Lab/tree/master/merit_rank](https://github.com/huaweicloud/ModelArts-Lab/tree/master/merit_rank)
  - 实践登记：将您 Issue 跟帖<b>链接</b>登记到 ModelArts-Lab 社区的 [积分总表](https://github.com/huaweicloud/ModelArts-Lab/blob/master/merit_rank/all_ranking.md) 里，按如下图操作获得 Issue 链接：
![获得链接](https://user-images.githubusercontent.com/24617067/59926305-9d6c2580-946c-11e9-93ca-6530b7fa2004.PNG)

- 【已上线实战】

  - [第一期：图像分类 (I)](https://github.com/huaweicloud/ModelArts-Lab/issues/49)，从头学起，基础更扎实，还可以累积更多积分哦！
  - [第二期：图像分类 (II)](https://github.com/huaweicloud/ModelArts-Lab/issues/113)，来从整体上熟悉 ModelArts 平台
  - [第三期：图像分类 (III) 模型参数&网络调优](https://github.com/huaweicloud/ModelArts-Lab/issues/219)，来深入了解深度学习模型优化技巧
  - [第四期：物体检测 (I) YOLO](https://github.com/huaweicloud/ModelArts-Lab/issues/402)，学习YOLO模型及ModelArts预置模型的应用
  - [第五期：物体检测 (II) Faster R-CNN](https://github.com/huaweicloud/ModelArts-Lab/issues/637)，学习Faster R-CNN模型的原理和实现
  - [第六期：物体检测 (III) Mask R-CNN](https://github.com/huaweicloud/ModelArts-Lab/issues/837)，学习使用Mask R-CNN模型进行实例分割
  - [第七期：自然语言处理(I) 命名实体识别](https://github.com/huaweicloud/ModelArts-Lab/issues/931)，学习使用BERT模型进行首个NLP任务
  - [第八期：自然语言处理(II) 文本分类](https://github.com/huaweicloud/ModelArts-Lab/issues/1025)，学习使用BERT模型进行NLP文本分类任务
  - [第九期：自然语言处理(III) 文本相似度分析](https://github.com/huaweicloud/ModelArts-Lab/issues/1087)，学习使用BERT模型进行NLP文本相似度分析任务
  - [第十期：自然语言处理(IV) 问答系统](https://github.com/huaweicloud/ModelArts-Lab/issues/1111)，学习使用BERT模型完成简单问答系统的搭建
  - [第十一期：人脸系列(I) 人脸检测](https://github.com/huaweicloud/ModelArts-Lab/issues/1177)，学习使用dlib完成对图片和视频中人脸区域的检测任务
  - [第十二期：人脸系列(II) 人脸检测](https://github.com/huaweicloud/ModelArts-Lab/issues/1248)，学习使用MTCNN模型和SSR模型完成对图片中人脸年龄的检测任务

**Comment by SUNNYDAYY** [comment]
## 华为云账号： S57123001

## 1. 人脸检测结果
<img width="659" alt="image" src="https://user-images.githubusercontent.com/19889290/67185098-a91a2980-f417-11e9-977e-a7a446bcd7f6.png">

## 2. 表情判断结果

<img width="659" alt="image" src="https://user-images.githubusercontent.com/19889290/67185098-a91a2980-f417-11e9-977e-a7a446bcd7f6.png">

**Comment by ilovescrapy** [comment]
华为云账号：G-washington
![image](https://user-images.githubusercontent.com/49826390/67192921-079ad400-f427-11e9-8b5a-275018183d10.png)
![image](https://user-images.githubusercontent.com/49826390/67192944-12556900-f427-11e9-87a1-e1d1b59a2e39.png)

**Comment by JUSxuaxuan** [comment]
# 华为云账号Shenshen1
## 人脸检测结果

![image](https://user-images.githubusercontent.com/50792908/67230345-b6fb9900-f46f-11e9-93f0-8805fade949b.png)

## 表情判断结果

![image](https://user-images.githubusercontent.com/50792908/67230358-bbc04d00-f46f-11e9-97cc-42180a10c4bc.png)

**Comment by PsyduckLiu** [comment]
**华为云账号HaolinLiu** 

**人脸检测结果**
<img width="665" alt="人脸检测结果1" src="https://user-images.githubusercontent.com/42675201/67271785-d5a07500-f4ed-11e9-9b65-bfed4c05698d.PNG">
<img width="836" alt="人脸识别结果表2" src="https://user-images.githubusercontent.com/42675201/67271789-d6d1a200-f4ed-11e9-8bd4-15c1ca88617a.PNG">

**表情判断结果**
<img width="561" alt="表情判断结果" src="https://user-images.githubusercontent.com/42675201/67271815-e5b85480-f4ed-11e9-9bd9-bcbff72a5a33.PNG">

**Comment by GitLD** [comment]
# 华为云账号： 
**Estein**
# 1. 人脸检测结果
![image](https://user-images.githubusercontent.com/30947306/67349139-aafbfe00-f579-11e9-9eff-c1807654c962.png)
# 2. 表情判断结果
![image](https://user-images.githubusercontent.com/30947306/67349091-80aa4080-f579-11e9-9b48-a8e3535b31eb.png)

**Comment by zxzxzxygithub** [comment]
华为云账号： zhengyx
1. 人脸检测结果
![image](https://user-images.githubusercontent.com/7334714/67381610-c2110f00-f5be-11e9-90cc-94bb38ea7a66.png)
2. 表情判断结果
![image](https://user-images.githubusercontent.com/7334714/67381632-cfc69480-f5be-11e9-9b29-ef392c6eac15.png)

**Comment by huxian123** [comment]
华为云账号：huxian123
人脸检测结果
![人脸检测结果](https://user-images.githubusercontent.com/14010658/67449521-02b76980-f64d-11e9-8e58-1927bc7ed570.jpg)
表情判断结果
![表情判断结果](https://user-images.githubusercontent.com/14010658/67449516-ffbc7900-f64c-11e9-9c5f-53e08c269c86.jpg)

**Comment by zhaocheng2006** [comment]
华为云账号： zhaocheng2006
1. 人脸检测结果
![QQ浏览器截图20191024111413](https://user-images.githubusercontent.com/19867088/67452217-19fa5500-f655-11e9-8065-349a7f64e44a.png)
![QQ浏览器截图20191024111314](https://user-images.githubusercontent.com/19867088/67452228-1ebf0900-f655-11e9-9278-da3565b6ef4e.png)

2. 表情判断结果
![QQ浏览器截图20191024111347](https://user-images.githubusercontent.com/19867088/67452238-27afda80-f655-11e9-876e-4440a5feda66.png)

**Comment by leighshanie** [comment]
```
华为云账号： pr0d1gy
```
## 1. 人脸检测结果
<img width="870" alt="Screenshot 2019-10-24 at 12 09 36" src="https://user-images.githubusercontent.com/43928576/67452958-9130e880-f657-11e9-9ee9-34a2a0e32755.png">

## 2. 表情判断结果
<img width="759" alt="Screenshot 2019-10-24 at 12 10 20" src="https://user-images.githubusercontent.com/43928576/67452961-9726c980-f657-11e9-983b-889690e3e426.png">

**Comment by jimmy9778** [comment]
华为云账号： jimmybhb
**1. 人脸检测结果**
![1571894674(1)](https://user-images.githubusercontent.com/26534432/67455962-c8a49280-f661-11e9-83e3-c3981446ef0b.png)
**2. 表情判断结果**
![1571894770(1)](https://user-images.githubusercontent.com/26534432/67456002-e40f9d80-f661-11e9-9635-b5dcad9352cc.png)

**Comment by work20** [comment]
华为云账号huawei018

人脸检测结果
![image](https://user-images.githubusercontent.com/49552789/67457955-97c75c00-f667-11e9-9f7e-fa420a33de39.png)


表情判断结果
![image](https://user-images.githubusercontent.com/49552789/67457981-a6ae0e80-f667-11e9-9e8a-02e3e90200d6.png)

**Comment by qq1187** [comment]
华为云账号：DwardZ
1. 人脸检测结果：
![人脸检测结果](https://user-images.githubusercontent.com/54825849/67491048-d9c3c280-f6a6-11e9-844c-922aa36d5421.JPG)
2. 表情判断结果：
![表情判断结果](https://user-images.githubusercontent.com/54825849/67491073-e47e5780-f6a6-11e9-9b89-94d3c872468d.JPG)

**Comment by fujilongcairns** [comment]
华为云账号fujilong
人脸检测结果
![0001](https://user-images.githubusercontent.com/53346990/67554347-c9145a80-f741-11e9-8bb5-bccbaf00adcf.png)
表情判断结果
![0002](https://user-images.githubusercontent.com/53346990/67554376-d92c3a00-f741-11e9-94f2-322df88859e9.png)

**Comment by cnfox0273** [comment]
华为云账号: cnfox0273
- 人脸检测结果
![Xnip2019-10-25_16-10-37](https://user-images.githubusercontent.com/10017051/67555889-c23b1700-f744-11e9-9aba-46f978a4fcb7.jpg)
- 表情判断结果
![Xnip2019-10-25_16-11-07](https://user-images.githubusercontent.com/10017051/67555902-c7986180-f744-11e9-8dd4-44ea4e586d3a.jpg)

**Comment by zhangjin318** [comment]
华为云账号 zhangjin0318
人脸检测结果：
![0001](https://user-images.githubusercontent.com/54631303/67571267-23bfad80-f766-11e9-98f5-9a74e2813867.jpg)
表情判断结果：
![0002](https://user-images.githubusercontent.com/54631303/67571271-26220780-f766-11e9-8690-7be53143e62c.jpg)

**Comment by hellfire0820-ty** [comment]
华为云账号： hellfire0925
1. 人脸检测结果
![1](https://user-images.githubusercontent.com/51829730/67578352-d991f880-f774-11e9-9d5b-ff769596dbcf.jpg)

2. 表情判断结果
![2](https://user-images.githubusercontent.com/51829730/67578366-e3b3f700-f774-11e9-9b48-f0f8321e726b.jpg)

**Comment by linteng0718** [comment]
华为云账号： linteng0718

人脸检测结果
![}X_G55%PA8C2RV)C{4DI~2E](https://user-images.githubusercontent.com/52825289/67584245-c46e9700-f77f-11e9-9710-e947490580bd.jpg)


表情判断结果
![{V_S`()} A9B~V6LCTHOO{Q](https://user-images.githubusercontent.com/52825289/67584251-c8021e00-f77f-11e9-8718-f04c0141ca3f.png)

**Comment by cnlile** [comment]
## 华为云账号：cnlile
### 人脸检测结果
![ImageText](https://github.com/cnlile/huawei_modelart_experiments/blob/master/phase13/detector.png?raw=true)
### 表情判断结果
![ImageText](https://github.com/cnlile/huawei_modelart_experiments/blob/master/phase13/result.png?raw=true)

**Comment by heran0912** [comment]
华为云账号：cnlile
1、人脸检测结果
<img width="414" alt="1" src="https://user-images.githubusercontent.com/45565034/67612290-fad60180-f7d3-11e9-8243-0174ac64ba6f.png">
2、表情判断结果
<img width="319" alt="2" src="https://user-images.githubusercontent.com/45565034/67612294-fdd0f200-f7d3-11e9-9447-7153599295ca.png">

**Comment by katzkuraki** [comment]
华为云账号：katzkuraki
1、人脸检测结果
![image](https://user-images.githubusercontent.com/26533491/67614680-d83eeb00-f7c9-11e9-8075-04cfed03fc88.png)

2、表情判断结果
![image](https://user-images.githubusercontent.com/26533491/67614681-dbd27200-f7c9-11e9-82bd-31a82d1c53df.png)

**Comment by g807504297** [comment]
华为云账号: zhangke12
1.人脸检测结果
![2019-10-26 19_27_02-test](https://user-images.githubusercontent.com/49725840/67618854-161e2c80-f827-11e9-9ec1-5cf7df9a3641.png)
2.表情判断结果
![2019-10-26 19_27_24-test](https://user-images.githubusercontent.com/49725840/67618857-21715800-f827-11e9-95e8-86122797e01b.png)

**Comment by chensw37** [comment]
华为云帐号：chensw37
1.人脸检测结果
![image](https://user-images.githubusercontent.com/48547196/67620526-82565b80-f83a-11e9-8729-14c9ca8d393b.png)
![image](https://user-images.githubusercontent.com/48547196/67620528-83878880-f83a-11e9-9191-a5541c3cdea8.png)
2表情判断结果
![image](https://user-images.githubusercontent.com/48547196/67620532-8a160000-f83a-11e9-838c-b2c8dc95e455.png)

**Comment by menglixiaoyi** [comment]
华为云账号：menglixiaoyi

1. 人脸检测结果
![13-1](https://user-images.githubusercontent.com/40586867/67621006-2510d900-f83f-11e9-9bd5-318c59dcdcb6.png)
2. 表情判断结果
![13-2](https://user-images.githubusercontent.com/40586867/67621011-293cf680-f83f-11e9-9d03-ae4d09ad77b9.png)

**Comment by LgyLab** [comment]
华为云账号：hawking

人脸检测结果
![2019-10-27-01-15-48](https://user-images.githubusercontent.com/47567011/67623406-6d3bf580-f857-11e9-9e5a-044e6cac6ef9.png)

表情判断结果
![2019-10-27-01-15-55](https://user-images.githubusercontent.com/47567011/67623407-72994000-f857-11e9-8348-b7f73e0b9936.png)

**Comment by linus086** [comment]
华为云账号：linus_cn

1. 人脸检测结果
![1](https://user-images.githubusercontent.com/49775221/67635449-6d44ff80-f902-11e9-8490-3ab7b13d717c.png)

2. 表情判断结果
![2](https://user-images.githubusercontent.com/49775221/67635451-703ff000-f902-11e9-9a84-c1159c7921c3.png)

**Comment by vvbushiwo** [comment]
华为云账号：vvbushiwo
1、人脸检测结果
![人脸检测结果](https://user-images.githubusercontent.com/28918407/67638226-16005880-f91d-11e9-9b2c-a9967954090d.JPG)

2、表情判断结果
![表情判断结果](https://user-images.githubusercontent.com/28918407/67638229-1bf63980-f91d-11e9-981d-0919ef51a426.JPG)

**Comment by wuyi1405** [comment]
华为云账号：wuyicom
1. 人脸检测结果
![1](https://user-images.githubusercontent.com/25198497/67647416-3f48d500-f96d-11e9-9598-ac458d00b49e.PNG)
2. 表情判断结果
![2](https://user-images.githubusercontent.com/25198497/67647466-67d0cf00-f96d-11e9-8822-6e242848ceb6.PNG)

**Comment by wangxw8746** [comment]
华为云账号：wangxw8746
**1.人脸检测结果**
![人脸检测结果](https://user-images.githubusercontent.com/55222843/67651441-e7fe3100-f97b-11e9-8a59-995ec6f9f7d1.png)
**2.表情判断结果**
![表情判断结果](https://user-images.githubusercontent.com/55222843/67651450-f3515c80-f97b-11e9-9330-0d3b91bae7e7.png)

**Comment by iflwx** [comment]
华为云账号：iflwx_jan

1.人脸检测结果
![image](https://user-images.githubusercontent.com/21186468/67661508-65399e00-f99c-11e9-8586-d6f70d313d4b.png)

2.表情判断结果
![image](https://user-images.githubusercontent.com/21186468/67661511-68cd2500-f99c-11e9-8322-485af8cb5e16.png)

Note: 判断结果为happy？不过考虑到只有'angry', 'disgust', 'fear', 'happy', 'sad', 'surprise', 'neutral'这7种标签，最接近的好像确实是happy

**Comment by qq1187** [comment]
华为云账号：DwardZ
1.人脸检测结果
![1](https://user-images.githubusercontent.com/54825849/67661781-045e9580-f99d-11e9-88eb-94bdb7f634db.JPG)
2. 表情判断结果
![2](https://user-images.githubusercontent.com/54825849/67661794-0d4f6700-f99d-11e9-81ee-8fb305138ffb.jpg)

**Comment by benmcq2019** [comment]
华为云账号：maomaode
1.人脸检测结果
![1](https://user-images.githubusercontent.com/46392381/67663188-e47ca100-f99f-11e9-972f-5879115f6f1c.png)
2. 表情判断结果
![2](https://user-images.githubusercontent.com/46392381/67663202-ec3c4580-f99f-11e9-925b-5782958dcbcb.png)

**Comment by JaneConan** [comment]
华为云账号： JaneConan

- 人脸检测结果

![image](https://user-images.githubusercontent.com/26090153/67663781-37a32380-f9a1-11e9-99be-abcd400bee4a.png)

- 表情判断结果

![image](https://user-images.githubusercontent.com/26090153/67663840-54d7f200-f9a1-11e9-8ddc-a07eca8fd8ba.png)

**Comment by NightExp** [comment]
华为云账号： NightEzp
1. 人脸检测结果
![1](https://user-images.githubusercontent.com/26305246/67672144-43e3ac80-f9b2-11e9-8fbe-a7d659bf1c0d.jpg)

2. 表情判断结果
![2](https://user-images.githubusercontent.com/26305246/67672149-46460680-f9b2-11e9-8292-baefaf831695.jpg)

**Comment by abing197** [comment]
华为云账号： hw55862329
人脸检测结果
![11](https://user-images.githubusercontent.com/54518295/67674272-01709e80-f9b7-11e9-8207-f8c0ecf7843e.png)
表情判断结果
![22](https://user-images.githubusercontent.com/54518295/67674285-06355280-f9b7-11e9-92fd-bc7861975651.png)

**Comment by leewishyuanfang** [comment]
华为云账号： leewish_yuanfang
人脸检测结果
![1](https://user-images.githubusercontent.com/50704594/67683272-0ab83600-f9cc-11e9-8c71-e81952579753.PNG)

表情判断结果
![2](https://user-images.githubusercontent.com/50704594/67683280-0db32680-f9cc-11e9-8d30-c6a6a1ca8664.PNG)

**Comment by flatefish** [comment]
华为云账号： zhenyuxu
人脸检测结果
![lab13-1](https://user-images.githubusercontent.com/52328047/67683890-22dc8500-f9cd-11e9-92c0-6c8953d6b57c.png)

表情判断结果
![lab13-2](https://user-images.githubusercontent.com/52328047/67683931-3a1b7280-f9cd-11e9-8c00-6951144f283d.png)

**Comment by xuyanbo03** [comment]
华为云账号：awebone

**1.人脸检测结果**
![13-1](https://user-images.githubusercontent.com/22814355/67692258-dd26b900-f9da-11e9-979d-1c9c53796a7d.png)

**2.表情判断结果**
![13-2](https://user-images.githubusercontent.com/22814355/67692279-e6178a80-f9da-11e9-9038-5fcd32756fae.png)

**Comment by Xuagent** [comment]
华为云账号: XuQiang_atisz

人脸检测结果
![image](https://user-images.githubusercontent.com/40290640/67730025-7df29400-fa2e-11e9-87e4-98ad31ef8706.png)

表情判断结果
![image](https://user-images.githubusercontent.com/40290640/67730028-8054ee00-fa2e-11e9-8cb0-d4d613cdec69.png)

**Comment by huangxunan** [comment]
华为云账号：huangxunan029
人脸检测结果：
![微信截图_20191029101814](https://user-images.githubusercontent.com/42038958/67732401-2fe18e80-fa36-11e9-86d9-7e958f30fcd2.png)

表情检测：
![微信截图_20191029101740](https://user-images.githubusercontent.com/42038958/67732405-33751580-fa36-11e9-822b-0f941e50431f.png)

**Comment by zeewie** [comment]
华为云账号: ZowieZz

人脸检测结果
![微信截图_20191029111458](https://user-images.githubusercontent.com/45626020/67734982-99b16680-fa3d-11e9-929b-efb2cb8fab61.png)
表情判断结果
![微信截图_20191029111545](https://user-images.githubusercontent.com/45626020/67734985-a33ace80-fa3d-11e9-9e3a-0b002ea6d358.png)

**Comment by zhujie2006** [comment]
## 华为云账号：
### zhujie_2006
### 1.人脸检测结果
![1](https://user-images.githubusercontent.com/7458297/67736648-50fcac00-fa43-11e9-841d-807a0b7795a8.png)
### 2.表情判断结果
![2](https://user-images.githubusercontent.com/7458297/67736649-51954280-fa43-11e9-8ff6-1812c77e3fe9.png)

**Comment by wangxw8746** [comment]
华为云账号：wangxw8746
**人脸检测结果**
![人脸检测结果](https://user-images.githubusercontent.com/55222843/67821856-751ac480-faf9-11e9-824a-ae5ebac85fdb.png)
**表情判断结果**
![表情判断结果](https://user-images.githubusercontent.com/55222843/67821868-7fd55980-faf9-11e9-9d96-80cdfcba66e2.png)

**Comment by hqchqc** [comment]
### **华为云账号： beanBag**
**1. 人脸检测结果**
![hw54](https://user-images.githubusercontent.com/51051157/67829784-650fde80-fb13-11e9-971c-4cb376bcc41e.png)
**2. 表情判断结果**
![hw55](https://user-images.githubusercontent.com/51051157/67829797-6e994680-fb13-11e9-9678-e647873d518b.png)

**Comment by GCRoots** [comment]
华为云账号：EasyArch-W
1. 人脸检测结果
![13-1.PNG](https://upload-images.jianshu.io/upload_images/19233840-a47acb223c46a93e.PNG?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

2. 表情判断结果
![13-2.PNG](https://upload-images.jianshu.io/upload_images/19233840-b8006cf5e21faa00.PNG?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by 15940983626** [comment]
华为云账号： 15940983626

人脸检测结果
![31](https://user-images.githubusercontent.com/20301808/67832923-1f0c4800-fb1e-11e9-9469-91d55165026f.png)

表情判断结果
![32](https://user-images.githubusercontent.com/20301808/67833108-b1ace700-fb1e-11e9-8b4e-b66ad2836afb.png)

**Comment by zss33266** [comment]
华为云账号： zss33266
1. 人脸检测结果
![image](https://user-images.githubusercontent.com/52277737/67843834-ba5de700-fb37-11e9-9343-565f2db1d772.png)

2. 表情判断结果
![image](https://user-images.githubusercontent.com/52277737/67843878-c5b11280-fb37-11e9-8b7b-8e8cc87b183a.png)

**Comment by chentiebang** [comment]
华为云账号：chenzeshi
人脸检测结果
![人脸检测](https://user-images.githubusercontent.com/56393767/67914235-7bc53c80-fbca-11e9-837e-f3e0cf129fc3.png)
表情判断结果
![表情判断](https://user-images.githubusercontent.com/56393767/67914244-7f58c380-fbca-11e9-9254-c79377cc5f10.png)

**Comment by linzhuofeng** [comment]
华为云账号：linzhuofeng

人脸检测结果
![人脸检测](https://user-images.githubusercontent.com/54026207/67920893-dbc6dd80-fbe0-11e9-9c82-8651503bd423.png)

表情判断结果
![表情判断](https://user-images.githubusercontent.com/54026207/67920895-dd90a100-fbe0-11e9-91d7-9a40410f4657.png)

**Comment by Assassinbelief** [comment]
华为云账号：hw60990420
1.人脸检测结果
![face_detection](https://user-images.githubusercontent.com/35474918/67932870-b0072000-fbff-11e9-9d47-f871c38e8924.png)

2.表情判断结果
![ans](https://user-images.githubusercontent.com/35474918/67932876-b4333d80-fbff-11e9-8aa0-1752ddd2e123.png)

**Comment by dengxues** [comment]
华为云账号： dengxues
1. 人脸检测结果
![Snap4](https://user-images.githubusercontent.com/39674995/67948139-17cd6300-fc20-11e9-94f6-27dfd4477a7e.jpg)

2. 表情判断结果
![Snap1](https://user-images.githubusercontent.com/39674995/67948207-421f2080-fc20-11e9-84d7-a7ea28cce859.jpg)

**Comment by donghui** [comment]
华为云账号：jerredh

1.人脸检测结果
![1](https://user-images.githubusercontent.com/449127/67951796-2408ee80-fc27-11e9-81f7-f4ca947302c2.PNG)

2.表情判断结果
![2](https://user-images.githubusercontent.com/449127/67951803-279c7580-fc27-11e9-9d9b-0627974570c1.PNG)

**Comment by linjiachen** [comment]
华为云账号：linjiachen
人脸检测结果
![人脸检测](https://user-images.githubusercontent.com/56219099/68002252-eb0e5f80-fca2-11e9-898e-ba1ebd2d2cc2.png)

表情判断结果
![表情判断](https://user-images.githubusercontent.com/56219099/68002244-d9c55300-fca2-11e9-9312-3f0137bd576d.png)

**Comment by zaojun** [comment]
华为云账号： hw11323995
1. 人脸检测结果
![13-1](https://user-images.githubusercontent.com/41715744/68027770-2f731d00-fcee-11e9-87bd-aedd263b6c78.jpg)
![13-2](https://user-images.githubusercontent.com/41715744/68027771-300bb380-fcee-11e9-931f-00706b786a65.jpg)

2. 表情判断结果
![13-3](https://user-images.githubusercontent.com/41715744/68027793-3d28a280-fcee-11e9-9ecd-833725fc9fce.jpg)

**Comment by daibin** [comment]
华为云账号： ynxdb2002
人脸检测结果
![31](https://user-images.githubusercontent.com/3481210/68083771-e6df6f00-fe67-11e9-8ab8-4fdf0558bc3e.JPG)
表情判断结果
![32](https://user-images.githubusercontent.com/3481210/68083776-efd04080-fe67-11e9-9d66-41b24108ff79.JPG)

**Comment by from1996iter** [comment]
华为云账号： lishuimo
1. 人脸检测结果
![image](https://user-images.githubusercontent.com/32993056/68085060-822c1080-fe77-11e9-9489-716e080d9e69.png)

2. 表情判断结果
![image](https://user-images.githubusercontent.com/32993056/68085062-86f0c480-fe77-11e9-9b74-a86704eaf2f4.png)

**Comment by ciyiming** [comment]
华为云账号：ciyiming
1. 人脸检测结果
![01](https://user-images.githubusercontent.com/46000048/68096159-e091d700-fee9-11e9-80de-2a2d3e2d6ad2.jpg)
2. 表情判断结果
![02](https://user-images.githubusercontent.com/46000048/68096168-e4bdf480-fee9-11e9-86f0-741e94ee914f.jpg)

**Comment by Rrrocky98** [comment]
华为云账号：Rocky98

1. 人脸检测结果


![1](https://user-images.githubusercontent.com/57023564/68113896-c24eca00-ff2f-11e9-9c77-7e6e57be93f3.png)


2. 表情判断结果

![2](https://user-images.githubusercontent.com/57023564/68113952-e90d0080-ff2f-11e9-9cef-ed1a8178c473.png)

**Comment by shaoyong96** [comment]
### 华为云账号：hw54910600
## 人脸检测结果
![1](https://user-images.githubusercontent.com/44717964/68269365-8d0fbc80-0094-11ea-9f0b-2c973f092cd3.png)
## 表情判断结果
![2](https://user-images.githubusercontent.com/44717964/68269404-a9abf480-0094-11ea-8207-7fc0332841a5.png)

**Comment by linian09** [comment]
华为云账号：hw06587017
1. 人脸检测结果
![QQ截图20191107214039](https://user-images.githubusercontent.com/57095223/68393630-63938580-01a7-11ea-9de5-72c49e2b70c0.png)
2. 表情判断结果
![QQ截图20191107214058](https://user-images.githubusercontent.com/57095223/68393636-64c4b280-01a7-11ea-9374-ce4a275f10ca.png)

**Comment by longshenhuigui** [comment]
华为云账号： hw50582000
1. 人脸检测结果

![)}{Y%5U{3{PLEXNO0 5U _N](https://user-images.githubusercontent.com/52161158/68443246-5493ee00-020e-11ea-8624-57d1a9b85170.png)

2. 表情判断结果
![XFAH(})A_HO$~2ZOGHP_OC6](https://user-images.githubusercontent.com/52161158/68443252-5a89cf00-020e-11ea-96df-b9ea4039126d.png)

**Comment by Alex20250** [comment]
华为云账号:Alex2025
人脸检测结果
![5](https://user-images.githubusercontent.com/52554168/68448331-23bbb500-021e-11ea-9343-e458a55e5f93.png)


表情判断结果
![6](https://user-images.githubusercontent.com/52554168/68448333-25857880-021e-11ea-80a1-4265ba6ce836.png)

**Comment by dengleiy** [comment]
华为云账号： hw40732214

人脸检测结果
![132](https://user-images.githubusercontent.com/57354648/68465050-ab201d00-024c-11ea-9b6d-e8869da8ba50.jpg)
表情判断结果
![131](https://user-images.githubusercontent.com/57354648/68465080-ba06cf80-024c-11ea-844a-5d48d3babfb5.jpg)

**Comment by hw38169653** [comment]
华为云账号：hw38169653
人脸检测结果
![1](https://user-images.githubusercontent.com/57040710/68469729-b6c41180-0255-11ea-8001-d0353923003d.jpg)
表情判断结果
![2](https://user-images.githubusercontent.com/57040710/68469763-c4799700-0255-11ea-9912-75ee99f39eb4.jpg)

**Comment by Carex-Chunhui** [comment]
华为云账号： hw28207081
人脸检测结果
![image](https://user-images.githubusercontent.com/49952978/68494725-decd6800-0289-11ea-9f1e-102bbb59c7a9.png)
![image](https://user-images.githubusercontent.com/49952978/68494730-e1c85880-0289-11ea-8f80-9d0ca5f9bee9.png)
![image](https://user-images.githubusercontent.com/49952978/68494739-e4c34900-0289-11ea-8170-00d914203393.png)

表情判断结果
![image](https://user-images.githubusercontent.com/49952978/68494751-eab92a00-0289-11ea-98c6-d188807b508d.png)

**Comment by Edward-Wbsz** [comment]
华为云账号： hw28321490
人脸检测结果：
[
![`ISK9R1QC}H3)2AYUQA3 }X](https://user-images.githubusercontent.com/56443127/68525032-707bba80-0308-11ea-8acf-af21654f2bc9.png)
](url)

表情判断结果：
[
![`H6LCV2I4UG5TGU9)UEXG6T](https://user-images.githubusercontent.com/56443127/68525039-796c8c00-0308-11ea-811a-baf9eefdc1e4.png)
](url)

**Comment by hw60701982** [comment]
华为云账号： hw60701982
人脸检测结果：
![QQ图片20191109161859](https://user-images.githubusercontent.com/57257548/68526018-72e31200-0312-11ea-9d80-56fbee1f4a65.png)
表情判断结果：
![QQ图片20191109161931](https://user-images.githubusercontent.com/57257548/68526046-a7ef6480-0312-11ea-8554-59a6d445727e.png)

**Comment by uflexnihao** [comment]
华为云账号： uflexnihao

人脸检测结果1
![a1人脸检测](https://user-images.githubusercontent.com/6821672/68526104-6c08cf00-0313-11ea-960f-fa2c72d5b59a.PNG)

表情判断1
![a2表情判断](https://user-images.githubusercontent.com/6821672/68526112-7b881800-0313-11ea-89d8-3739b532fdf3.PNG)

人脸检测2
![b1人脸检测](https://user-images.githubusercontent.com/6821672/68526141-ae321080-0313-11ea-8cc0-9f0bf98b88a9.PNG)


表情判断2
![b2表情判断](https://user-images.githubusercontent.com/6821672/68526143-b25e2e00-0313-11ea-9c1a-4f1d9cc24583.PNG)

**Comment by chenliang613** [comment]
活动结束，本issue关闭！
