### ISSUE TITLE
【华为云 ModelArts-Lab AI实战营】第十五期：OCR系列（I）文字区域检测

### ISSUE THREAD

**Issue by sunbo57123** [huaweicloud/ModelArts-Lab#1395]
# 【华为云 ModelArts-Lab AI实战营】第十五期

- 相信访问本页面的您，已经是《华为云 ModelArts-Lab AI实战营》前十四期的的学员，并且已经熟悉ModelArts平台的基本操作了。本期是OCR（光学字符检测）的第一期内容，这次我们将通过CTPN完成图片中文字区域检测的训练和推理任务。

- **本期实战，会涉及少量存储费用，请保证账户余额至少1元参与本期活动，请见[费用 FAQ 说明](https://github.com/huaweicloud/ModelArts-Lab/blob/master/docs/faqs.md)。**

## 本期实战营参与说明

> 本期实战为OCR系列第一期，通过学习CTPN模型的训练和推理，对图片中的文字区域进行预测。案例分为CTPN的模型构建，模型训练和推理，完成对文字区域的提取。

1. 【本期实战内容】
  - 第十五期案例：[文字区域检测案例](https://github.com/huaweicloud/ModelArts-Lab/tree/master/notebook/DL_ocr_ctpn_text_detection)

2. 【加入实战微信群】
  - 欢迎您自由加入本期实战营的微信群，与 ModelArts 社区开发者一起交流
  - 请添加 “华为云 EI 微信小助手” 后，拉您入群（微信号：huaweisecretary）

3. 【留下实战记录】
  - 请在本 Issue 下方跟帖反馈：<b>华为云账号 + 完成截图</b>。[点击跟帖反馈本期实战截图](https://github.com/huaweicloud/ModelArts-Lab/issues/1395#new_comment_field)
  - 反馈信息格式，请参考如下 @SUNNYDAYY  的样例

4. 【本期积分规则】
    - <b>本期实战需要反馈2个截图，获得1个积分，虽然可以使用我们提供的图片，但建议大家自己上传自定义图片</b>：
            - <b>预测结果</b>
            - <b>筛选合并结果</b>
    - <b>注意，请在截图中体现出个人标识</b>

    - 本期实战获得额外积分的方式包括但不限于：分享CTPN论文心得，分析CTPN源码，贡献中文数据集，提高模型表现等，贡献文章和拓展案例请参照[contrib](https://github.com/huaweicloud/ModelArts-Lab/tree/master/contrib)。获取额外积分结果将由社区 committer 共同讨论商定。

5. 【手动停止服务】
  - 实验完成后，请**手动停止**占用云资源的服务，如：停止 “开发环境” 中所创建的 Notebook 以及 “部署上线”-“在线服务” 中所部署的在线服务，以避免因持续占用云资源导致资源包无谓消耗和欠费发生。需使用时，再启动即可。

6. 【获得实践积分】
  - 完成实战记录并回帖的开发者，请提交 Pull Request (PR) 到 [积分总表](https://github.com/huaweicloud/ModelArts-Lab/blob/master/merit_rank/all_ranking.md)，反馈您的实践、积分和贡献点，[具体操作流程在此](https://github.com/huaweicloud/ModelArts-Lab/wiki/Pull-Requests-%E6%9B%B4%E6%96%B0%E7%A7%AF%E5%88%86)。社区 Committers 核实后，合并 PR，积分正式生效。
  - 积分规则： [https://github.com/huaweicloud/ModelArts-Lab/tree/master/merit_rank](https://github.com/huaweicloud/ModelArts-Lab/tree/master/merit_rank)
  - 实践登记：将您 Issue 跟帖<b>链接</b>登记到 ModelArts-Lab 社区的 [积分总表](https://github.com/huaweicloud/ModelArts-Lab/blob/master/merit_rank/all_ranking.md) 里，按如下图操作获得 Issue 链接：
![获得链接](https://user-images.githubusercontent.com/24617067/59926305-9d6c2580-946c-11e9-93ca-6530b7fa2004.PNG)

- 【已上线实战】

  - [第一期：图像分类 (I)](https://github.com/huaweicloud/ModelArts-Lab/issues/49)，从头学起，基础更扎实，还可以累积更多积分哦！
  - [第二期：图像分类 (II)](https://github.com/huaweicloud/ModelArts-Lab/issues/113)，来从整体上熟悉 ModelArts 平台
  - [第三期：图像分类 (III) 模型参数&网络调优](https://github.com/huaweicloud/ModelArts-Lab/issues/219)，来深入了解深度学习模型优化技巧
  - [第四期：物体检测 (I) YOLO](https://github.com/huaweicloud/ModelArts-Lab/issues/402)，学习YOLO模型及ModelArts预置模型的应用
  - [第五期：物体检测 (II) Faster R-CNN](https://github.com/huaweicloud/ModelArts-Lab/issues/637)，学习Faster R-CNN模型的原理和实现
  - [第六期：物体检测 (III) Mask R-CNN](https://github.com/huaweicloud/ModelArts-Lab/issues/837)，学习使用Mask R-CNN模型进行实例分割
  - [第七期：自然语言处理(I) 命名实体识别](https://github.com/huaweicloud/ModelArts-Lab/issues/931)，学习使用BERT模型进行首个NLP任务
  - [第八期：自然语言处理(II) 文本分类](https://github.com/huaweicloud/ModelArts-Lab/issues/1025)，学习使用BERT模型进行NLP文本分类任务
  - [第九期：自然语言处理(III) 文本相似度分析](https://github.com/huaweicloud/ModelArts-Lab/issues/1087)，学习使用BERT模型进行NLP文本相似度分析任务
  - [第十期：自然语言处理(IV) 问答系统](https://github.com/huaweicloud/ModelArts-Lab/issues/1111)，学习使用BERT模型完成简单问答系统的搭建
  - [第十一期：人脸系列(I) 人脸检测](https://github.com/huaweicloud/ModelArts-Lab/issues/1177)，学习使用dlib完成对图片和视频中人脸区域的检测任务
  - [第十二期：人脸系列(II) 年龄检测](https://github.com/huaweicloud/ModelArts-Lab/issues/1248)，学习使用MTCNN模型和SSR模型完成对图片中人脸年龄的检测任务
  - [第十三期：人脸系列(III) 表情检测](https://github.com/huaweicloud/ModelArts-Lab/issues/1343)，学习使用深度学习网络完成对图片中人脸表情的分类任务
  - [第十四期：人脸系列(IV) 人脸识别](https://github.com/huaweicloud/ModelArts-Lab/issues/1364)，学习使用FaceNet网络完成人脸识别任务

**Comment by SUNNYDAYY** [comment]
华为云账号：S57123001
1. 预测结果
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/19889290/67567077-da6a6080-f75b-11e9-9fec-c84288f13bdc.png">

2. 筛选合并后的结果
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/19889290/67567095-e6562280-f75b-11e9-946a-0f88aa6ad4a2.png">

**Comment by fujilongcairns** [comment]
华为云账号：fujilong
预测结果
![01](https://user-images.githubusercontent.com/53346990/67577314-cc740a00-f772-11e9-8b70-da0c31149289.jpg)
筛选合并后的结果
![02](https://user-images.githubusercontent.com/53346990/67577317-ce3dcd80-f772-11e9-9eba-9b2e3e55f047.jpg)

**Comment by PsyduckLiu** [comment]
**华为云账号：HaolinLiu** 
**预测结果**
![预测结果](https://user-images.githubusercontent.com/42675201/67611836-de37ca80-f7cf-11e9-81a8-a471cd1b573c.PNG)

**筛选合并后的结果**
![筛选合并后的结果](https://user-images.githubusercontent.com/42675201/67611843-e98af600-f7cf-11e9-8598-65a1ea6e0f33.PNG)

**Comment by fjqsun** [comment]
华为云账号：fjqsun
预测结果:
![01](https://user-images.githubusercontent.com/51841701/67612797-88b3eb80-f7d8-11e9-83f4-890dfd479d6b.JPG)
筛选合并后的结果:
![02](https://user-images.githubusercontent.com/51841701/67612801-94071700-f7d8-11e9-800a-8f3103413df3.JPG)

**Comment by heran0912** [comment]
华为云账号：heran0912
1、预测结果:
<img width="560" alt="3" src="https://user-images.githubusercontent.com/45565034/67612816-d2043b00-f7d8-11e9-92a1-b2ab337c70b4.png">
2、筛选合并后的结果:
<img width="576" alt="4" src="https://user-images.githubusercontent.com/45565034/67612820-d7fa1c00-f7d8-11e9-9729-960a399e5726.png">

**Comment by ilovescrapy** [comment]
华为云账号：G-washington
![image](https://user-images.githubusercontent.com/49826390/67612923-0f1cfd00-f7da-11e9-98ac-41502913f781.png)
![image](https://user-images.githubusercontent.com/49826390/67612929-1e9c4600-f7da-11e9-9ef7-a5f0a1e07809.png)

**Comment by leighshanie** [comment]
```
华为云账号：pr0d1gy
```
## 1. 预测结果
<img width="1046" alt="Screenshot 2019-10-26 at 11 05 24" src="https://user-images.githubusercontent.com/43928576/67613482-aa18d580-f7e0-11e9-9731-37759d0f35b3.png">

## 2. 筛选合并后的结果
<img width="1065" alt="Screenshot 2019-10-26 at 11 05 16" src="https://user-images.githubusercontent.com/43928576/67613484-ad13c600-f7e0-11e9-939d-33cd6e5adca4.png">

**Comment by GitLD** [comment]
# 华为云账号：
**Estein**
# 1、预测结果:
![image](https://user-images.githubusercontent.com/30947306/67613734-74292080-f7e3-11e9-89fe-fc354e381f78.png)

# 2、筛选合并后的结果:
![image](https://user-images.githubusercontent.com/30947306/67613738-81dea600-f7e3-11e9-8620-67090899178b.png)

**Comment by katzkuraki** [comment]
华为云账号：katzkuraki
1、预测结果:
![image](https://user-images.githubusercontent.com/26533491/67615114-a7ae7f80-f7d0-11e9-974b-2b614d1b5b09.png)

2、筛选合并后的结果:
![image](https://user-images.githubusercontent.com/26533491/67615116-aaa97000-f7d0-11e9-90d4-297d835b7bde.png)

**Comment by cnfox0273** [comment]
华为云账号：cnfox0273
- 预测结果
![Xnip2019-10-26_21-24-19](https://user-images.githubusercontent.com/10017051/67620237-5a192d80-f837-11e9-809a-6661843c32cc.jpg)
- 筛选合并结果
![Xnip2019-10-26_21-25-51](https://user-images.githubusercontent.com/10017051/67620239-600f0e80-f837-11e9-8704-a2252f66798f.jpg)

**Comment by zhangjin318** [comment]
华为云账号：zhangjin0318

预测结果
![0001](https://user-images.githubusercontent.com/54631303/67620505-736fa900-f83a-11e9-9c6c-f853386a8f31.jpg)
筛选合并结果
![0002](https://user-images.githubusercontent.com/54631303/67620507-75396c80-f83a-11e9-91c0-f4c7ed3c099e.jpg)

**Comment by menglixiaoyi** [comment]
华为云账号：menglixiaoyi
1.预测结果
![15-1](https://user-images.githubusercontent.com/40586867/67621395-1972e180-f842-11e9-851a-d833626302db.png)

2.筛选合并后的结果
![15-2](https://user-images.githubusercontent.com/40586867/67621399-1ed02c00-f842-11e9-968a-1687fa8068e0.png)

**Comment by hellfire0820-ty** [comment]
hellfire0925
1、预测结果:
![1](https://user-images.githubusercontent.com/51829730/67622563-dae32400-f84d-11e9-873e-382efa8605fa.jpg)

2、筛选合并后的结果:
![2](https://user-images.githubusercontent.com/51829730/67622570-e898a980-f84d-11e9-9e78-3de5155094e5.jpg)

**Comment by LgyLab** [comment]
华为云账号: hawking 

- 预测结果
![2019-10-27-16-33-37](https://user-images.githubusercontent.com/47567011/67632004-9fda0280-f8d8-11e9-8e85-09f8539272ff.png)


筛选合并结果
![2019-10-27-16-33-49](https://user-images.githubusercontent.com/47567011/67632007-a7011080-f8d8-11e9-8be9-8ce1539c5768.png)

**Comment by jimmy9778** [comment]
华为云账号：**jimmybhb**

**1、预测结果:**
![1572232238(1)](https://user-images.githubusercontent.com/26534432/67649353-b84b2b00-f973-11e9-8f7c-7ab37f29bae3.png)
**2、筛选合并结果：**
![1572232271(1)](https://user-images.githubusercontent.com/26534432/67649358-bc774880-f973-11e9-9dcf-575f15c5afe3.png)

**Comment by benmcq2019** [comment]
华为云账号:maomaode

1、预测结果：
![1](https://user-images.githubusercontent.com/46392381/67649395-e3357f00-f973-11e9-8a90-01a29d852127.png)
2、筛选合并结果：
![2](https://user-images.githubusercontent.com/46392381/67649400-ef214100-f973-11e9-895c-4c0419ff5382.png)

**Comment by g807504297** [comment]
华为云账号: zhangke12
# 1.预测结果
![2019-10-28 13_41_00-test](https://user-images.githubusercontent.com/49725840/67654520-c9526700-f988-11e9-96db-ba4cb34f1043.png)

# 2.筛选后合并的结果
![2019-10-28 13_41_14-test](https://user-images.githubusercontent.com/49725840/67654527-ce171b00-f988-11e9-9040-2f256f3dd99d.png)

**Comment by huxian123** [comment]
华为云账号：huxian123
预测结果
![预测结果](https://user-images.githubusercontent.com/14010658/67654719-70370300-f989-11e9-96f1-a11bae2a4cf1.jpg)
筛选合并后的结果
![筛选合并后的结果](https://user-images.githubusercontent.com/14010658/67654725-75944d80-f989-11e9-90af-62c8c2d5b1f1.jpg)

**Comment by linus086** [comment]
华为云账号：linus_cn

1. 预测结果
![1](https://user-images.githubusercontent.com/49775221/67655025-56e28680-f98a-11e9-9ee1-42731b88ec15.png)

2. 筛选合并后的结果
![2](https://user-images.githubusercontent.com/49775221/67655030-5a760d80-f98a-11e9-9483-155fe700dba8.png)

**Comment by benmcq2019** [comment]
华为云账号：maomaode
1、预测结果
![1](https://user-images.githubusercontent.com/46392381/67663398-59e87180-f9a0-11e9-8e9d-3aed5c08c1e4.png)
2、筛选合并后的结果
![2](https://user-images.githubusercontent.com/46392381/67663407-62d94300-f9a0-11e9-9486-126cdfa0ec5d.png)

**Comment by iflwx** [comment]
华为云账号：iflwx_jan

- 预测结果
![image](https://user-images.githubusercontent.com/21186468/67668047-23175900-f9aa-11e9-93ea-8a1e83d35beb.png)

- 筛选合并结果
![image](https://user-images.githubusercontent.com/21186468/67668058-290d3a00-f9aa-11e9-87e6-1b4141cc6003.png)

**Comment by abing197** [comment]
华为云账号：hw55862329
预测结果
![1111](https://user-images.githubusercontent.com/54518295/67674452-76dc6f00-f9b7-11e9-9481-b9dac6b24727.png)
筛选合并结果
![2222](https://user-images.githubusercontent.com/54518295/67674461-7c39b980-f9b7-11e9-9418-8cf12e1c8807.png)

**Comment by NightExp** [comment]
华为云账号：NightEzp
预测结果
![1](https://user-images.githubusercontent.com/26305246/67676565-c1141f00-f9bc-11e9-8659-7931637c5ef2.jpg)

筛选合并后的结果
 
![2](https://user-images.githubusercontent.com/26305246/67676571-c2dde280-f9bc-11e9-8c80-284dd56ed8ac.jpg)

**Comment by wuyi1405** [comment]
华为云账号：wuyicom
1.预测结果
![1](https://user-images.githubusercontent.com/25198497/67679850-fd4b7d80-f9c4-11e9-8045-989a19b64077.PNG)
2.筛选合并后的结果
![2](https://user-images.githubusercontent.com/25198497/67679869-0b999980-f9c5-11e9-84ac-3755074b1e4f.PNG)

**Comment by JUSxuaxuan** [comment]
# 华为云账号 Shenshen1
## 预测结果
![image](https://user-images.githubusercontent.com/50792908/67682172-b7dd7f00-f9c9-11e9-88d5-e3fe71eb4f1c.png)

## 筛选合并结果
![image](https://user-images.githubusercontent.com/50792908/67682197-c035ba00-f9c9-11e9-8ea8-3f4c8429003b.png)

**Comment by work20** [comment]
华为云账号：huawei018

预测结果
![image](https://user-images.githubusercontent.com/49552789/67730215-55b76500-fa2f-11e9-810e-06936fa92035.png)

筛选合并后的结果
![image](https://user-images.githubusercontent.com/49552789/67730234-62d45400-fa2f-11e9-8afe-0084027aa977.png)

**Comment by JaneConan** [comment]
华为云账号：JaneConan

- 预测结果

![image](https://user-images.githubusercontent.com/26090153/67730288-8eefd500-fa2f-11e9-8842-ed41825b3c74.png)

- 筛选合并后的结果

![image](https://user-images.githubusercontent.com/26090153/67730321-a9c24980-fa2f-11e9-9886-79a1d62dcc87.png)

**Comment by huangxunan** [comment]
华为云账号：huangxunan029

预测结果
![微信截图_20191029103926](https://user-images.githubusercontent.com/42038958/67733680-07f42a00-fa3a-11e9-81cb-d59ec1c97bb7.png)

筛选合并后的结果
![微信截图_20191029103914](https://user-images.githubusercontent.com/42038958/67733684-0aef1a80-fa3a-11e9-8c94-14bd76c86828.png)

**Comment by Xuagent** [comment]
华为云账号：XuQiang_atisz

预测结果
![image](https://user-images.githubusercontent.com/40290640/67734354-d4b29a80-fa3b-11e9-8431-8891c6fdc98e.png)

筛选合并结果
![image](https://user-images.githubusercontent.com/40290640/67734360-d8deb800-fa3b-11e9-8d44-924a6f3344c7.png)

**Comment by zeewie** [comment]
华为云账号：ZowieZz 

预测结果
![微信截图_20191029114506](https://user-images.githubusercontent.com/45626020/67736194-b0f25300-fa41-11e9-8b74-40f633f8f95f.png)
筛选合并结果
![微信截图_20191029114526](https://user-images.githubusercontent.com/45626020/67736231-d7b08980-fa41-11e9-8a60-73fd4ae00e75.png)

**Comment by zhujie2006** [comment]
## 华为云账号：
### zhujie_2006
### 1.预测结果
![1](https://user-images.githubusercontent.com/7458297/67742148-29fba580-fa56-11e9-9871-11f02cac1d32.png)
### 2.筛选合并结果
![2](https://user-images.githubusercontent.com/7458297/67742149-29fba580-fa56-11e9-8fda-79be869766c9.png)

**Comment by Bourne-M** [comment]
华为云账号：Bourne-M
1.预测结果
![1](https://user-images.githubusercontent.com/13611481/67753924-77850c00-fa70-11e9-8130-d9b4d62f5486.png)
2.筛选合并结果
![2](https://user-images.githubusercontent.com/13611481/67753950-84096480-fa70-11e9-933b-8982f968e6b2.png)

**Comment by leewishyuanfang** [comment]
华为云账号：leewish_yuanfang

    预测结果
![1](https://user-images.githubusercontent.com/50704594/67771197-d3f92300-fa92-11e9-99f9-d51b27b275cc.PNG)

    筛选合并后的结果
![2](https://user-images.githubusercontent.com/50704594/67771311-030f9480-fa93-11e9-9de5-a4670006fcd2.PNG)

**Comment by hqchqc** [comment]
华为云账号：beanBag
**1.预测结果**
![hw59](https://user-images.githubusercontent.com/51051157/67837820-e45cdc80-fb2a-11e9-992b-33faa6c1e2d3.png)
**2、筛选合并后的结果:**
![hw60](https://user-images.githubusercontent.com/51051157/67837879-06565f00-fb2b-11e9-9763-71ed0fc1ceed.png)

**Comment by 15940983626** [comment]
华为云账号：15940983626
预测结果:
![51](https://user-images.githubusercontent.com/20301808/67839605-fccef600-fb2e-11e9-853e-14e4f420c848.png)
筛选合并结果
![52](https://user-images.githubusercontent.com/20301808/67839645-13754d00-fb2f-11e9-9d4d-a71d121fd13f.png)

**Comment by flatefish** [comment]
华为云账号：zhenyuxu
1.预测结果
![lab15-1](https://user-images.githubusercontent.com/52328047/67851884-5bec3500-fb46-11e9-8b22-68317f97b404.png)

2、筛选合并后的结果:
![lab15-2](https://user-images.githubusercontent.com/52328047/67851922-6e666e80-fb46-11e9-915e-b9da386a7b4e.png)

**Comment by chentiebang** [comment]
华为云账号：chenzeshi
预测结果
![预测](https://user-images.githubusercontent.com/56393767/67916371-75d25a00-fbd0-11e9-8b30-6c6f0a3179f8.png)
筛选合并后的结果
![筛选合并](https://user-images.githubusercontent.com/56393767/67916374-78cd4a80-fbd0-11e9-9874-de7e6bafa7d1.png)

**Comment by linzhuofeng** [comment]
华为云账号：linzhuofeng

预测结果
![预测](https://user-images.githubusercontent.com/54026207/67920980-33654900-fbe1-11e9-9445-b754f8ff8c40.png)

筛选合并后的结果
![筛选合并](https://user-images.githubusercontent.com/54026207/67920986-34967600-fbe1-11e9-9728-871903e92708.png)

**Comment by zhaocheng2006** [comment]
华为云账号：zhaocheng2006

    预测结果
![15-1](https://user-images.githubusercontent.com/19867088/67931908-d461fd00-fbfd-11e9-8ea6-97b612236d2d.png)

    筛选合并后的结果
![15-3](https://user-images.githubusercontent.com/19867088/67931926-ddeb6500-fbfd-11e9-87f0-f06f6fe6f1f3.png)

**Comment by zaojun** [comment]
华为云账号:hw11323995
预测结果
![15-1](https://user-images.githubusercontent.com/41715744/67947608-f5871580-fc1e-11e9-84a6-371c0471fe9a.jpg)

筛选合并后的结果
![15-2](https://user-images.githubusercontent.com/41715744/67947629-020b6e00-fc1f-11e9-850b-512f88bf965e.jpg)

**Comment by cnlile** [comment]
## 华为云账号:cnlile
### 预测结果
![ImageText](https://github.com/cnlile/huawei_modelart_experiments/blob/master/phase15/PredictionResults.png?raw=true)
### 筛选合并后的结果
![ImageText](https://github.com/cnlile/huawei_modelart_experiments/blob/master/phase15/FilterMergeResults.png?raw=true)

**Comment by donghui** [comment]
华为云账号：jerredh

1.预测结果
![image](https://user-images.githubusercontent.com/449127/67957468-9df1a580-fc30-11e9-88c0-7bc2d0f1613b.png)

2.筛选合并后的结果
![image](https://user-images.githubusercontent.com/449127/67957496-aba72b00-fc30-11e9-9721-92fcd4dabf5a.png)

**Comment by daibin** [comment]
华为云账号：ynxdb2002
1.预测结果
![51](https://user-images.githubusercontent.com/3481210/67957665-e9a44f00-fc30-11e9-8b66-e5e53e3c1ef1.JPG)

2.筛选后的结果
![52](https://user-images.githubusercontent.com/3481210/67957696-f3c64d80-fc30-11e9-81e1-211f131e4723.JPG)

**Comment by linjiachen** [comment]
华为云账号：linjiachen
预测结果
![预测](https://user-images.githubusercontent.com/56219099/68002285-1abd6780-fca3-11e9-94bc-6bffa0d8c0de.png)

筛选合并后的结果
![筛选合并](https://user-images.githubusercontent.com/56219099/68002286-1c872b00-fca3-11e9-80f0-ba1de0576de3.png)

**Comment by GCRoots** [comment]
华为云账号：EasyArch-W

预测结果
![15-1.PNG](https://upload-images.jianshu.io/upload_images/19233840-c3e950c12478a7c1.PNG?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

筛选合并后的结果
![15-2.PNG](https://upload-images.jianshu.io/upload_images/19233840-0f123e26fba65d31.PNG?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by GCRoots** [comment]
华为云账号：EasyArch-W
预测结果
![15-1.PNG](https://upload-images.jianshu.io/upload_images/19233840-c3e950c12478a7c1.PNG?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

筛选合并后的结果
![15-2.PNG](https://upload-images.jianshu.io/upload_images/19233840-0f123e26fba65d31.PNG?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by dengxues** [comment]
华为云账号：dengxues

1、预测结果
![Snap3](https://user-images.githubusercontent.com/39674995/68065107-3a19ca80-fd5f-11e9-9c47-5f660d2c8714.jpg)

2、筛选合并后的结果
![Snap4](https://user-images.githubusercontent.com/39674995/68065114-561d6c00-fd5f-11e9-83fe-7e92a20f113e.jpg)

**Comment by zhaohengxuan** [comment]
华为云账号：zhaohengxuan 
1.预测结果
![image](https://user-images.githubusercontent.com/44860940/68066339-59215800-fd71-11e9-81d6-1e7715458a48.png)
2.	筛选合并后的结果
![image](https://user-images.githubusercontent.com/44860940/68066351-62122980-fd71-11e9-96af-18ba9c1edc96.png)

**Comment by Assassinbelief** [comment]
华为云账号：hw60990420
**1.预测结果**
![1predicted](https://user-images.githubusercontent.com/35474918/68067516-bc67b600-fd82-11e9-9e69-62c88a057d08.png)

**2.筛选合并结果**
![2combine](https://user-images.githubusercontent.com/35474918/68067518-beca1000-fd82-11e9-9522-59cb0cf4c93f.png)

**Comment by from1996iter** [comment]
华为云账号：lishuimo

预测结果
![image](https://user-images.githubusercontent.com/32993056/68085416-d638f400-fe7b-11e9-963c-14de7cdbe7f1.png)

筛选合并后的结果
![image](https://user-images.githubusercontent.com/32993056/68085423-ecdf4b00-fe7b-11e9-8a7a-c25fdbebe2b1.png)

**Comment by vvbushiwo** [comment]
华为云账号：vvbushiwo
预测结果：
![预测](https://user-images.githubusercontent.com/28918407/68095357-bd642900-fee3-11e9-85e2-ca8f4b9dcc8e.JPG)

筛选合并后的结果：
![合并后](https://user-images.githubusercontent.com/28918407/68095362-c3f2a080-fee3-11e9-808f-9272035c5861.JPG)

**Comment by ciyiming** [comment]
华为云账号：ciyiming

1.预测结果
![01](https://user-images.githubusercontent.com/46000048/68097379-b2b09080-fef1-11e9-8797-ae06f8d93de4.jpg)
2.筛选合并后的结果
![02](https://user-images.githubusercontent.com/46000048/68097380-b47a5400-fef1-11e9-824f-ce8d414cb03c.jpg)

**Comment by Rrrocky98** [comment]
华为云账号：Rocky98

1.预测结果
![1](https://user-images.githubusercontent.com/57023564/68114190-68023900-ff30-11e9-8442-e7440665f99e.png)

2.筛选合并后的结果
![2](https://user-images.githubusercontent.com/57023564/68114212-73556480-ff30-11e9-88db-091ce5f24959.png

**Comment by Rrrocky98** [comment]
华为云账号：Rocky98

1.预测结果
![1](https://user-images.githubusercontent.com/57023564/68114292-9bdd5e80-ff30-11e9-93fa-2ec67e93dc8e.png)

2.筛选合并后的结果
![2](https://user-images.githubusercontent.com/57023564/68114305-a13aa900-ff30-11e9-8be6-6b07242c575b.png)

**Comment by zss33266** [comment]
华为云账号：zss33266

预测结果
![image](https://user-images.githubusercontent.com/52277737/68177740-3fc41a00-ffc4-11e9-9c1a-d919e7770dbd.png)

筛选合并后的结果
![image](https://user-images.githubusercontent.com/52277737/68177769-4e123600-ffc4-11e9-8f3c-0ababa29ecf3.png)

**Comment by shaoyong96** [comment]
### 华为云账号：hw54910600
## 预测结果
![1](https://user-images.githubusercontent.com/44717964/68271132-9e5bc780-009a-11ea-92ff-e502360c33fc.png)
## 筛选合并后的结果
![2](https://user-images.githubusercontent.com/44717964/68271139-a1ef4e80-009a-11ea-9976-a24ee0a2b653.png)

**Comment by wangxw8746** [comment]
华为云帐号：wangxw8746
**预测结果**
![预测结果](https://user-images.githubusercontent.com/55222843/68351122-74a7ac80-013d-11ea-9faa-298247a861d4.png)
**筛选合并后的结果**
![筛选合并后的结果](https://user-images.githubusercontent.com/55222843/68351143-85f0b900-013d-11ea-9893-b66fdeb1773a.png)

**Comment by xuyanbo03** [comment]
华为云帐号：awebone

**1.预测结果**
![15-1](https://user-images.githubusercontent.com/22814355/68379601-24563c00-0189-11ea-945f-035529ef574d.jpg)

**2.筛选合并后的结果**
![15-2](https://user-images.githubusercontent.com/22814355/68379620-2f10d100-0189-11ea-9d1a-05b3ac826628.jpg)

**Comment by linian09** [comment]
华为云账号：hw06587017
预测结果
![QQ截图20191107220316](https://user-images.githubusercontent.com/57095223/68395326-75c2f300-01aa-11ea-819e-4982a7577e52.png)
筛选合并后的结果
![QQ截图20191107220329](https://user-images.githubusercontent.com/57095223/68395334-78bde380-01aa-11ea-92a5-823e4f201277.png)

**Comment by Alex20250** [comment]
华为云账号：Alex2025

预测结果
![10](https://user-images.githubusercontent.com/52554168/68449462-1dc7d300-0222-11ea-8f9b-24d6a31f01ed.png)


筛选合并后的结果
![11](https://user-images.githubusercontent.com/52554168/68449464-1f919680-0222-11ea-9be0-6605e4667566.png)

**Comment by dengleiy** [comment]
华为云账号：hw40732214

预测结果
![151](https://user-images.githubusercontent.com/57354648/68473322-a152e580-025d-11ea-9762-03f1752b6d94.jpg)
筛选合并后的结果
![152](https://user-images.githubusercontent.com/57354648/68473331-aadc4d80-025d-11ea-9a53-31619100c5d9.jpg)

**Comment by hw38169653** [comment]
华为云账号：hw38169653
预测结果
![1](https://user-images.githubusercontent.com/57040710/68476445-a7e55b00-0265-11ea-998f-2e1c286fefdd.jpg)
筛选合并后的结果
![2](https://user-images.githubusercontent.com/57040710/68476544-f0047d80-0265-11ea-9ecd-929e4f207516.jpg)

**Comment by longshenhuigui** [comment]
华为云账号：S57123001

预测结果
![HDZG(WTQ1%_ACQ5Q@Q}~S`Y](https://user-images.githubusercontent.com/52161158/68483432-850f7280-0276-11ea-957d-81f2cbfc7e5d.png)


筛选合并后的结果
![(2B7(43YYM53Q02H3_E1A{E](https://user-images.githubusercontent.com/52161158/68483476-9b1d3300-0276-11ea-89dc-8d8e3be0e4cd.png)

**Comment by longshenhuigui** [comment]
华为云账号：hw50582000

预测结果
![HDZG(WTQ1%_ACQ5Q@Q}~S`Y](https://user-images.githubusercontent.com/52161158/68483822-331b1c80-0277-11ea-8f36-5b854c89e7b1.png)


筛选合并后的结果
![(2B7(43YYM53Q02H3_E1A{E](https://user-images.githubusercontent.com/52161158/68483867-4201cf00-0277-11ea-830e-11087a6ed0ff.png)

**Comment by Carex-Chunhui** [comment]
华为云账号：hw28207081
预测结果
![image](https://user-images.githubusercontent.com/49952978/68499259-b9ddf280-0293-11ea-9ff6-0cc8bc6f1895.png)

筛选合并后的结果
![image](https://user-images.githubusercontent.com/49952978/68499266-bea2a680-0293-11ea-8565-88ca5f893ee1.png)

**Comment by hw60701982** [comment]
华为云账号：hw60701982
预测结果
![QQ图片20191109164126](https://user-images.githubusercontent.com/57257548/68526146-b427f180-0313-11ea-902a-dd1e60e44cbd.png)
筛选合并后的结果
![QQ图片20191109164158](https://user-images.githubusercontent.com/57257548/68526149-bbe79600-0313-11ea-9c7f-ee7924e941c8.png)

**Comment by uflexnihao** [comment]
华为云账号： uflexnihao

预测结果1
![1预测结果](https://user-images.githubusercontent.com/6821672/68526282-0fa6af00-0315-11ea-8948-ed8e2dcfbb52.PNG)

合并后1
![2合并结果](https://user-images.githubusercontent.com/6821672/68526292-1df4cb00-0315-11ea-9c96-69f09db76b61.PNG)

预测结果2
![3预测结果](https://user-images.githubusercontent.com/6821672/68526298-2947f680-0315-11ea-87c3-f9b07bcc8561.PNG)

合并后2
![4合并结果](https://user-images.githubusercontent.com/6821672/68526302-32d15e80-0315-11ea-805b-74b6bc1dd8a2.PNG)

**Comment by Edward-Wbsz** [comment]
华为云账号： hw28321490
1.预测结果：
[
![6WXXV@BC@X)(S4P1SYVR7_A](https://user-images.githubusercontent.com/56443127/68527378-11766f80-0321-11ea-88a5-a9ca5666f6c1.png)
](url)

2.合并结果：
[
![)TJI{R W`%F GZRU0L`0PKN](https://user-images.githubusercontent.com/56443127/68527384-1affd780-0321-11ea-8726-30d72aa051b7.png)
](url)

**Comment by chenliang613** [comment]
活动结束，本issue关闭！
