### ISSUE TITLE
ai 身份识别的攻防测试

### ISSUE THREAD

**Issue by benmcq2019** [huaweicloud/ModelArts-Lab#140]
故事是这样的，在华为ModelArtsModelArts实验班交流群里水了大半个月，每天不是调戏华为助理就是骚扰华为老师。没事就水一篇文章混积分。终于，有一天助理发了一份微认证活动。我打开一看，福利多多啊！于是就开始了（ModelArts实验班第一期），完成了两个训练得了两个么么哒，哎。不甘心就点开了认证考试，发现居然还是进行身份证照片及人脸识别的！故事的高潮也就来了。
开心的上传我帅气身份证：

![微信图片_20190621120123_副本](https://user-images.githubusercontent.com/46392381/60106464-d7ecff80-9797-11e9-9c94-d13d33c841c4.jpg)

然后就.......
![微信图片_20190625222408](https://user-images.githubusercontent.com/46392381/60106755-53e74780-9798-11e9-9b8c-33c3fb8bc9f1.png)
尴尬 尴尬 光头就不认咯 
![0090c7d3ca6d6b6159fc3c0b467f457](https://user-images.githubusercontent.com/46392381/60106834-71b4ac80-9798-11e9-97a9-4dc7b9172d8d.png)
带上假的 也不让过
这不能等头发长出来再考啊！！！余光看到了桌面上的美图秀秀！！！嘿嘿！！！
![微信图片_20190625181054_副本_副本](https://user-images.githubusercontent.com/46392381/60106977-a9bbef80-9798-11e9-8035-16dba073c314.jpg)
再试
![微信图片_20190625223312_副本](https://user-images.githubusercontent.com/46392381/60107488-952c2700-9799-11e9-9571-28e0db544c3d.png)
哈哈哈哈哈哈！！！
最后考了72勉强过了，哎。就等助理发书补课补课！！！

**Comment by chenliang613** [comment]
哈哈，感谢分享。这个故事可以写一个个人博客， github issues里咱们讨论技术问题。 这个issue，我关闭了？

**Comment by benmcq2019** [comment]
哦哦哦 嘿嘿 嗯嗯 好的 嘿嘿



------------------ 原始邮件 ------------------
发件人: "Liang Chen"<notifications@github.com>; 
发送时间: 2019年6月26日(星期三) 下午5:47
收件人: "huaweicloud/ModelArts-Lab"<ModelArts-Lab@noreply.github.com>; 
抄送: "优雅的疯子"<393403787@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [huaweicloud/ModelArts-Lab] ai 身份识别的攻防测试 (#140)




哈哈，感谢分享。这个故事可以写一个个人博客， github issues里咱们讨论技术问题。 这个issue，我关闭了？
