### ISSUE TITLE
【华为云 ModelArts-Lab AI实战营】第十六期：OCR系列（I）字符检测

### ISSUE THREAD

**Issue by sunbo57123** [huaweicloud/ModelArts-Lab#1445]
# 【华为云 ModelArts-Lab AI实战营】第十六期

- 相信访问本页面的您，已经是《华为云 ModelArts-Lab AI实战营》前十五期的的学员，并且已经熟悉ModelArts平台的基本操作了。本期是OCR（光学字符检测）的第二期内容，这次我们将通过CRNN模型完成图片中字符的检测任务。

- **本期实战，会涉及少量存储费用，请保证账户余额至少1元参与本期活动，请见[费用 FAQ 说明](https://github.com/huaweicloud/ModelArts-Lab/blob/master/docs/faqs.md)。**

## 本期实战营参与说明

> 本期实战为OCR系列第一期，通过学习CTPN模型的训练和推理，对图片中的文字区域进行预测。案例分为CTPN的模型构建，模型训练和推理，完成对文字区域的提取。

1. 【本期实战内容】
  - 第十六期案例：[文字区域检测案例](https://github.com/huaweicloud/ModelArts-Lab/tree/master/notebook/DL_ocr_crnn_sequence_recognition)

2. 【加入实战微信群】
  - 欢迎您自由加入本期实战营的微信群，与 ModelArts 社区开发者一起交流
  - 请添加 “华为云 EI 微信小助手” 后，拉您入群（微信号：huaweisecretary）

3. 【留下实战记录】
  - 请在本 Issue 下方跟帖反馈：<b>华为云账号 + 完成截图</b>。[点击跟帖反馈本期实战截图](https://github.com/huaweicloud/ModelArts-Lab/issues/1445#new_comment_field)
  - 反馈信息格式，请参考如下 @SUNNYDAYY  的样例

4. 【本期积分规则】
    - <b>本期实战需要反馈1个截图，获得1个积分，虽然可以使用我们提供的图片，但建议大家自己上传自定义图片</b>：
            - <b>待检测图片</b>
            - <b>预测结果</b>

    - <b>注意，请在截图中体现出个人标识</b>

    - 本期实战获得额外积分的方式包括但不限于：分享CRNN论文心得，分析CRNN源码，贡献中文数据集，通过给出的训练代码和数据进行训练，提高模型表现等，贡献文章和拓展案例请参照[contrib](https://github.com/huaweicloud/ModelArts-Lab/tree/master/contrib)。获取额外积分结果将由社区 committer 共同讨论商定。

5. 【手动停止服务】
  - 实验完成后，请**手动停止**占用云资源的服务，如：停止 “开发环境” 中所创建的 Notebook 以及 “部署上线”-“在线服务” 中所部署的在线服务，以避免因持续占用云资源导致资源包无谓消耗和欠费发生。需使用时，再启动即可。

6. 【获得实践积分】
  - 完成实战记录并回帖的开发者，请提交 Pull Request (PR) 到 [积分总表](https://github.com/huaweicloud/ModelArts-Lab/blob/master/merit_rank/all_ranking.md)，反馈您的实践、积分和贡献点，[具体操作流程在此](https://github.com/huaweicloud/ModelArts-Lab/wiki/Pull-Requests-%E6%9B%B4%E6%96%B0%E7%A7%AF%E5%88%86)。社区 Committers 核实后，合并 PR，积分正式生效。
  - 积分规则： [https://github.com/huaweicloud/ModelArts-Lab/tree/master/merit_rank](https://github.com/huaweicloud/ModelArts-Lab/tree/master/merit_rank)
  - 实践登记：将您 Issue 跟帖<b>链接</b>登记到 ModelArts-Lab 社区的 [积分总表](https://github.com/huaweicloud/ModelArts-Lab/blob/master/merit_rank/all_ranking.md) 里，按如下图操作获得 Issue 链接：
![获得链接](https://user-images.githubusercontent.com/24617067/59926305-9d6c2580-946c-11e9-93ca-6530b7fa2004.PNG)

- 【已上线实战】

  - [第一期：图像分类 (I)](https://github.com/huaweicloud/ModelArts-Lab/issues/49)，从头学起，基础更扎实，还可以累积更多积分哦！
  - [第二期：图像分类 (II)](https://github.com/huaweicloud/ModelArts-Lab/issues/113)，来从整体上熟悉 ModelArts 平台
  - [第三期：图像分类 (III) 模型参数&网络调优](https://github.com/huaweicloud/ModelArts-Lab/issues/219)，来深入了解深度学习模型优化技巧
  - [第四期：物体检测 (I) YOLO](https://github.com/huaweicloud/ModelArts-Lab/issues/402)，学习YOLO模型及ModelArts预置模型的应用
  - [第五期：物体检测 (II) Faster R-CNN](https://github.com/huaweicloud/ModelArts-Lab/issues/637)，学习Faster R-CNN模型的原理和实现
  - [第六期：物体检测 (III) Mask R-CNN](https://github.com/huaweicloud/ModelArts-Lab/issues/837)，学习使用Mask R-CNN模型进行实例分割
  - [第七期：自然语言处理(I) 命名实体识别](https://github.com/huaweicloud/ModelArts-Lab/issues/931)，学习使用BERT模型进行首个NLP任务
  - [第八期：自然语言处理(II) 文本分类](https://github.com/huaweicloud/ModelArts-Lab/issues/1025)，学习使用BERT模型进行NLP文本分类任务
  - [第九期：自然语言处理(III) 文本相似度分析](https://github.com/huaweicloud/ModelArts-Lab/issues/1087)，学习使用BERT模型进行NLP文本相似度分析任务
  - [第十期：自然语言处理(IV) 问答系统](https://github.com/huaweicloud/ModelArts-Lab/issues/1111)，学习使用BERT模型完成简单问答系统的搭建
  - [第十一期：人脸系列(I) 人脸检测](https://github.com/huaweicloud/ModelArts-Lab/issues/1177)，学习使用dlib完成对图片和视频中人脸区域的检测任务
  - [第十二期：人脸系列(II) 年龄检测](https://github.com/huaweicloud/ModelArts-Lab/issues/1248)，学习使用MTCNN模型和SSR模型完成对图片中人脸年龄的检测任务
  - [第十三期：人脸系列(III) 表情检测](https://github.com/huaweicloud/ModelArts-Lab/issues/1343)，学习使用深度学习网络完成对图片中人脸表情的分类任务
  - [第十四期：人脸系列(IV) 人脸识别](https://github.com/huaweicloud/ModelArts-Lab/issues/1364)，学习使用FaceNet网络完成人脸识别任务
  - [第十五期：OCR系列(I) 文字区域检测](https://github.com/huaweicloud/ModelArts-Lab/issues/1395)，学习使用CTPN网络完成文字区域检测任务

**Comment by SUNNYDAYY** [comment]
华为云账号：S57123001
中文字符检测结果：
<img width="560" alt="image" src="https://user-images.githubusercontent.com/19889290/67638274-9030dd00-f91d-11e9-8d89-4957874e9a31.png">

**Comment by benmcq2019** [comment]
华为云账号：maomaode
测试图片：
![16](https://user-images.githubusercontent.com/46392381/67645183-18d16c80-f962-11e9-9196-ce8d0ba38eab.png)
![1](https://user-images.githubusercontent.com/46392381/67645188-24bd2e80-f962-11e9-885a-dacc5bf1973a.png)
中文字符检测结果：
![2](https://user-images.githubusercontent.com/46392381/67645202-2f77c380-f962-11e9-8526-301da1fab775.png)
终于抢到沙发啦！！！！

**Comment by ilovescrapy** [comment]
华为云账号：G-washington
![image](https://user-images.githubusercontent.com/49826390/67645239-71086e80-f962-11e9-9d65-bdd3329ec60d.png)
![image](https://user-images.githubusercontent.com/49826390/67645252-7ebdf400-f962-11e9-8245-46cd161780e7.png)

**Comment by heran0912** [comment]
华为云账号：heran0912
测试图片：
<img width="374" alt="1" src="https://user-images.githubusercontent.com/45565034/67648380-7a003c80-f970-11e9-98d3-dfd31a2d6357.png">

**Comment by cnfox0273** [comment]
华为云账号：cnfox0273
- 待检测图片
![Xnip2019-10-28_10-44-17](https://user-images.githubusercontent.com/10017051/67648359-6d7be400-f970-11e9-9b64-5d21856b67b3.jpg)
- 预测结果
![Xnip2019-10-28_10-47-10](https://user-images.githubusercontent.com/10017051/67648372-72d92e80-f970-11e9-9b87-a48a297f9d74.jpg)

**Comment by leighshanie** [comment]
```
华为云账号：pr0d1gy
```
## 1. 测试图片：
<img width="1101" alt="Screenshot 2019-10-28 at 11 25 06" src="https://user-images.githubusercontent.com/43928576/67649938-f8131200-f975-11e9-9e9f-520b0f627728.png">

## 2. 中文字符检测结果：
<img width="1102" alt="Screenshot 2019-10-28 at 11 26 07" src="https://user-images.githubusercontent.com/43928576/67650075-6b1c8880-f976-11e9-9fc2-16f98adf4ef8.png">

**Comment by jimmy9778** [comment]
华为云账号：**jimmybhb**

**1、测试图片：**
![1572233994(1)](https://user-images.githubusercontent.com/26534432/67650390-c1d69200-f977-11e9-8ef0-acf171ca82a7.png)
**2、中文字符检测结果：**
![1572234013(1)](https://user-images.githubusercontent.com/26534432/67650398-c9963680-f977-11e9-9c3f-8eca8e0154f3.png)

**Comment by katzkuraki** [comment]
华为云账号：katzkuraki
1、测试图片
![image](https://user-images.githubusercontent.com/26533491/67651977-0819fa00-f954-11e9-8e16-9a088993cc5e.png)

2、中文字符检测结果
![image](https://user-images.githubusercontent.com/26533491/67651982-0bad8100-f954-11e9-9a74-142e5c3a3852.png)

**Comment by PsyduckLiu** [comment]
**华为云账号：HaolinLiu
1、测试图片**
<img width="637" alt="测试图片" src="https://user-images.githubusercontent.com/42675201/67652332-65777080-f97f-11e9-8a6a-358dc19a074c.PNG">

**2、中文字符检测结果**
<img width="391" alt="中文字符检测结果" src="https://user-images.githubusercontent.com/42675201/67652343-71633280-f97f-11e9-834a-5688e7870d37.PNG">

**Comment by linus086** [comment]
华为云账号：linus_cn

1. 待检测图片
![1](https://user-images.githubusercontent.com/49775221/67654617-23532c80-f989-11e9-9507-b52ca6e7655e.png)

2. 预测结果
![2](https://user-images.githubusercontent.com/49775221/67654620-251cf000-f989-11e9-9dcf-7a45fa0c7b17.png)

**Comment by hellfire0820-ty** [comment]
华为云账号：hellfire0925
1、待检测图片
![1](https://user-images.githubusercontent.com/51829730/67658732-64513e00-f995-11e9-9a4b-b69d2fe7f38e.png)

2、预测结果
![2](https://user-images.githubusercontent.com/51829730/67658736-687d5b80-f995-11e9-8091-dee8d1b7c9c9.png)

**Comment by fjqsun** [comment]
华为云账号：fjqsun
1、待检测图片
<img width="629" alt="000001" src="https://user-images.githubusercontent.com/51841701/67663121-be570100-f99f-11e9-9ddc-f7ce0862b361.PNG">
2、预测结果
<img width="631" alt="000002" src="https://user-images.githubusercontent.com/51841701/67663135-c747d280-f99f-11e9-97d8-f4dc8918f456.PNG">

**Comment by iflwx** [comment]
华为云账号：iflwx_jan

- 待检测图片
![image](https://user-images.githubusercontent.com/21186468/67670247-725f8880-f9ae-11e9-87a8-151ebbb8a8e2.png)

- 预测结果
![image](https://user-images.githubusercontent.com/21186468/67670293-915e1a80-f9ae-11e9-8a4c-4573668a8153.png)

**Comment by abing197** [comment]
华为云账号：hw55862329
待检测图片
![1572259229(1)](https://user-images.githubusercontent.com/54518295/67674510-a4291d00-f9b7-11e9-85dd-9125a81159c3.png)
预测结果
![1572259235(1)](https://user-images.githubusercontent.com/54518295/67674515-a8edd100-f9b7-11e9-8c6e-3d6754f275d5.png)

**Comment by NightExp** [comment]
华为云账号：NightEzp
测试图片：
![1](https://user-images.githubusercontent.com/26305246/67677255-8c08cc00-f9be-11e9-9449-7585e8ded6ef.jpg)

中文字符检测结果：
![2](https://user-images.githubusercontent.com/26305246/67677259-8dd28f80-f9be-11e9-9952-b799d3c043e1.jpg)

**Comment by menglixiaoyi** [comment]
华为云账号：menglixiaoyi
测试图片：
![1](https://user-images.githubusercontent.com/40586867/67680221-c5910580-f9c5-11e9-8f52-aab9b483f15b.png)

中文字符检测结果：
![2](https://user-images.githubusercontent.com/40586867/67680227-c9bd2300-f9c5-11e9-8a00-e8a52993276c.png)

**Comment by wuyi1405** [comment]
华为云账号：wuyicom
1.测试图片
![1](https://user-images.githubusercontent.com/25198497/67680268-df324d00-f9c5-11e9-8d00-a45abce93a05.PNG)
2.中文字符检测结果
![2](https://user-images.githubusercontent.com/25198497/67680297-efe2c300-f9c5-11e9-92ef-d5751bdd97c1.PNG)

**Comment by JUSxuaxuan** [comment]
# 华为云账号Shenshen1
## 带预测图片
![image](https://user-images.githubusercontent.com/50792908/67690068-3856ac80-f9d7-11e9-9bdd-6891df289980.png)

## 预测结果
![image](https://user-images.githubusercontent.com/50792908/67690082-3f7dba80-f9d7-11e9-89ec-7fe0a86cb4a6.png)

### 自己的图片

![image](https://user-images.githubusercontent.com/50792908/67690102-4a384f80-f9d7-11e9-96ee-d12948c0de45.png)
准确度不高，~~ 啦啦啦 我的扩展由一期的方向

**Comment by work20** [comment]
华为云账号：huawei018

测试图片：
![image](https://user-images.githubusercontent.com/49552789/67730829-36b9d280-fa31-11e9-983f-01af0c06db87.png)

中文字符检测结果：
![image](https://user-images.githubusercontent.com/49552789/67730842-40dbd100-fa31-11e9-9180-275151c6cbe8.png)

**Comment by huxian123** [comment]
华为云账号：huxian123
待检测图片
![待检测图片](https://user-images.githubusercontent.com/14010658/67732807-8d2a0f80-fa37-11e9-819e-11adf5d18544.jpg)
预测结果
![预测结果](https://user-images.githubusercontent.com/14010658/67732811-91eec380-fa37-11e9-9819-480faa16f09a.jpg)

**Comment by huangxunan** [comment]
华为云账号：huangxunan029
检测图片与检测结果：
![微信截图_20191029104358](https://user-images.githubusercontent.com/42038958/67733402-3ae9ee00-fa39-11e9-8403-765c70cac5c7.png)

**Comment by Xuagent** [comment]
华为云账号：XuQiang_atisz

测试图片
![image](https://user-images.githubusercontent.com/40290640/67735845-66240b80-fa40-11e9-845b-c058532df5bc.png)

中文字符检测结果
![image](https://user-images.githubusercontent.com/40290640/67735848-691efc00-fa40-11e9-9392-a1aa57607a60.png)

**Comment by zhujie2006** [comment]
华为云账号：zhujie_2006
1.待检测图片
![1](https://user-images.githubusercontent.com/7458297/67742873-249f5a80-fa58-11e9-9436-6bd85cea9bd9.png)
2.预测结果
![2](https://user-images.githubusercontent.com/7458297/67742875-2537f100-fa58-11e9-8a87-20aa422b5a02.png)

**Comment by zeewie** [comment]
华为云账号：ZowieZz 
1.待检测图片
![微信截图_20191029165759](https://user-images.githubusercontent.com/45626020/67752083-4bb45700-fa6d-11e9-9444-cde42859e8d0.png)
2.预测结果
![微信截图_20191029165806](https://user-images.githubusercontent.com/45626020/67752090-4fe07480-fa6d-11e9-824e-343e7d8e85d8.png)

**Comment by zhangjin318** [comment]
华为云账号：zhangjin0318
1.待检测图片
![0111](https://user-images.githubusercontent.com/54631303/67770713-e2930a80-fa91-11e9-909b-9baf4a652f6d.jpg)

2.预测结果
![0112](https://user-images.githubusercontent.com/54631303/67770721-e58dfb00-fa91-11e9-9c3f-3fd983b95b56.jpg)

**Comment by leewishyuanfang** [comment]
华为云账号：S57123001
测试图片：

![1](https://user-images.githubusercontent.com/50704594/67771669-b5dff280-fa93-11e9-8205-927bb8dc6626.PNG)

中文字符检测结果：
![2](https://user-images.githubusercontent.com/50704594/67771721-cabc8600-fa93-11e9-8d06-abe5eea03a63.PNG)

**Comment by LgyLab** [comment]
华为云账号:hawking

- 待检测图片
![2019-10-29-21-37-43](https://user-images.githubusercontent.com/47567011/67772423-01df6700-fa95-11e9-852d-44e10e6747ed.png)
- 预测结果
![2019-10-29-21-41-30](https://user-images.githubusercontent.com/47567011/67772472-1459a080-fa95-11e9-9de6-08d756bd7c9b.png)

**Comment by fujilongcairns** [comment]
华为云账号:fujilong

待检测图片
![0001](https://user-images.githubusercontent.com/53346990/67773163-40c1ec80-fa96-11e9-9b2a-fb0318cd492c.jpg)

预测结果
![0002](https://user-images.githubusercontent.com/53346990/67773181-46b7cd80-fa96-11e9-9e30-1a3ebd82b075.jpg)

**Comment by hqchqc** [comment]
### **华为云账号： beanBag**
**1.测试图片**
![hw67](https://user-images.githubusercontent.com/51051157/67839318-54209680-fb2e-11e9-808e-5ad47b4c0f74.png)
**2.中文字符检测结果**
![hw68](https://user-images.githubusercontent.com/51051157/67839386-80d4ae00-fb2e-11e9-9aee-ecfacffa8724.png)

**Comment by 15940983626** [comment]
华为云账号： 15940983626
1.测试图片
![61](https://user-images.githubusercontent.com/20301808/67840442-e2961780-fb30-11e9-95aa-2d56ca859967.png)
2.中文字符检测结果
![62](https://user-images.githubusercontent.com/20301808/67840484-f9d50500-fb30-11e9-82f4-394be6bbe572.png)

**Comment by flatefish** [comment]
华为云账号： 15940983626
当图片与文字的比例大一些就识别错误
1.测试图片
![lab16-1](https://user-images.githubusercontent.com/52328047/67852277-18de9180-fb47-11e9-8bd9-4ee3143be5ff.png)

2.中文字符检测结果
![lab16-2](https://user-images.githubusercontent.com/52328047/67852382-46c3d600-fb47-11e9-97f8-6adb28c8ad26.png)

**Comment by chentiebang** [comment]
华为云账号：chenzeshi
1、测试图片：
![测试](https://user-images.githubusercontent.com/56393767/67917661-a61bf780-fbd4-11e9-9d26-cccbcf9c85a0.png)
2、中文字符检测结果：
![中文字符检测](https://user-images.githubusercontent.com/56393767/67917662-a916e800-fbd4-11e9-80d9-30fa8f2ccfad.png)

**Comment by linzhuofeng** [comment]
华为云账号：linzhuofeng

测试图片：
![测试](https://user-images.githubusercontent.com/54026207/67921042-614a8d80-fbe1-11e9-81d6-762cee0bb090.png)

中文字符检测结果：
![中文字符检测](https://user-images.githubusercontent.com/54026207/67921045-63145100-fbe1-11e9-9932-6a1b86065359.png)

**Comment by GitLD** [comment]
# 华为云账号：
**Estein**
# 测试图片：
![image](https://user-images.githubusercontent.com/30947306/67922296-55f96100-fbe5-11e9-8173-7caf31bf1922.png)
# 中文字符检测结果：
![image](https://user-images.githubusercontent.com/30947306/67922466-c43e2380-fbe5-11e9-8612-52e1df467580.png)

**Comment by zhaocheng2006** [comment]
华为云账号：zhaocheng2006
测试图片：
![16-1](https://user-images.githubusercontent.com/19867088/67932076-37539400-fbfe-11e9-95eb-dba78e9b8ca3.png)

中文字符检测结果：
![16-4](https://user-images.githubusercontent.com/19867088/67932101-40446580-fbfe-11e9-849a-2bcddbbdeed0.png)

**Comment by cnlile** [comment]
## 华为云账号：cnlile
### 测试图片：
![ImageText](https://github.com/cnlile/huawei_modelart_experiments/blob/master/phase16/test_img.png?raw=true)
### 中文字符检测结果：
![ImageText](https://github.com/cnlile/huawei_modelart_experiments/blob/master/phase16/test_result.png?raw=true)

**Comment by daibin** [comment]
华为云账号：ynxdb2002
测试图片：
![61](https://user-images.githubusercontent.com/3481210/67958765-aa76fd80-fc32-11e9-90c6-9328667228ba.JPG)


中文字符检测结果：

![62](https://user-images.githubusercontent.com/3481210/67958785-aea31b00-fc32-11e9-84d6-4f4613c9a6eb.JPG)

**Comment by linjiachen** [comment]
华为云账号：linjiachen
测试图片
![测试](https://user-images.githubusercontent.com/56219099/68002316-43456180-fca3-11e9-8f61-0b585670d79e.png)

中文字符检测结果
![中文字符检测](https://user-images.githubusercontent.com/56219099/68002325-49d3d900-fca3-11e9-9902-2122f46f4ec9.png)

**Comment by dengxues** [comment]
华为云账号：dengxues

测试图片：
![Snap10](https://user-images.githubusercontent.com/39674995/68065156-da6fef00-fd5f-11e9-843d-1b47e9312148.jpg)

中文字符检测结果：
![Snap11](https://user-images.githubusercontent.com/39674995/68065159-ef4c8280-fd5f-11e9-9f74-cab48e65a4e0.jpg)

**Comment by Assassinbelief** [comment]
华为云账号：hw60990420
**1.待检测图片**
![1Input](https://user-images.githubusercontent.com/35474918/68067621-d5716680-fd84-11e9-8113-e7e6fbc83d07.png)

**2.预测结果**
![2output](https://user-images.githubusercontent.com/35474918/68067622-d86c5700-fd84-11e9-9b45-056dd9945b08.png)

**Comment by zhaohengxuan** [comment]
华为云账号：zhaohengxuan 
1. 待检测图片
![image](https://user-images.githubusercontent.com/44860940/68069419-e62cd700-fd9a-11e9-9603-2019b5c361f9.png)
---灰度处理
![image](https://user-images.githubusercontent.com/44860940/68069426-f6dd4d00-fd9a-11e9-9093-15593c34d98c.png)
![image](https://user-images.githubusercontent.com/44860940/68069427-fb096a80-fd9a-11e9-97c8-1c9324bb39c3.png)
2.测试结果
![image](https://user-images.githubusercontent.com/44860940/68069428-0361a580-fd9b-11e9-9f62-38fb0b33b0af.png)
![image](https://user-images.githubusercontent.com/44860940/68069430-06f52c80-fd9b-11e9-9eb1-676ec87bc8e3.png)

**Comment by GCRoots** [comment]
华为云账号：EasyArch-W
测试图片：
![16-1.PNG](https://upload-images.jianshu.io/upload_images/19233840-c5e086fd9d5e25ce.PNG?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

中文字符检测结果：
![16-2.PNG](https://upload-images.jianshu.io/upload_images/19233840-2cd0235b2330da95.PNG?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by from1996iter** [comment]
华为云账号：lishuimo
测试图片：
![image](https://user-images.githubusercontent.com/32993056/68085521-be15a480-fe7c-11e9-9707-0e98e4ad8140.png)

中文字符检测结果：
![image](https://user-images.githubusercontent.com/32993056/68085528-ca016680-fe7c-11e9-990f-4a4e2e11124c.png)

**Comment by ciyiming** [comment]
华为云账号：ciyiming
测试图片：
![01](https://user-images.githubusercontent.com/46000048/68097630-18e9e300-fef3-11e9-83be-0094c1ad3b6d.jpg)
中文字符检测结果：
![02](https://user-images.githubusercontent.com/46000048/68097631-1ab3a680-fef3-11e9-900a-6f2a7f92dbc1.jpg)

**Comment by Rrrocky98** [comment]
华为云账号：Rocky98

1.测试图片

![1](https://user-images.githubusercontent.com/57023564/68114406-e52dae00-ff30-11e9-898c-c6bb50c7b45a.png)

2.测试结果

![2](https://user-images.githubusercontent.com/57023564/68114419-ea8af880-ff30-11e9-9bad-d325a4dc6fa5.png)

**Comment by zss33266** [comment]
华为云账号：zss33266
测试图片：
![image](https://user-images.githubusercontent.com/52277737/68177855-a1848400-ffc4-11e9-98d6-abee6876cea1.png)

中文字符检测结果：
![image](https://user-images.githubusercontent.com/52277737/68177864-a77a6500-ffc4-11e9-8c0e-a5e8c672dad4.png)

**Comment by vvbushiwo** [comment]
华为云账号：vvbushiwo
测试图片
![测试图片](https://user-images.githubusercontent.com/28918407/68260051-a6097500-0076-11ea-81c2-470282842333.JPG)

中文字符检测结果
![预测结果](https://user-images.githubusercontent.com/28918407/68260056-a9046580-0076-11ea-8b1e-e45afe904d20.JPG)

**Comment by shaoyong96** [comment]
### 华为云账号：hw54910600
## 测试图片
![1](https://user-images.githubusercontent.com/44717964/68271990-4bcfda80-009d-11ea-9b03-dd2b54de93c0.png)
## 中文字符检测结果
![2](https://user-images.githubusercontent.com/44717964/68271995-4f636180-009d-11ea-96d8-c272adeef4d2.png)

**Comment by JaneConan** [comment]
华为云账号：JaneConan
测试图片：
![666](https://user-images.githubusercontent.com/26090153/68355635-d6224800-014a-11ea-8bbf-603be98657b9.png)

中文字符检测结果：
![image](https://user-images.githubusercontent.com/26090153/68355618-c60a6880-014a-11ea-86d3-f987a6c379e5.png)

意会意会🐟🐟🐟

**Comment by xuyanbo03** [comment]
华为云账号：awebone

**测试**
![16-1](https://user-images.githubusercontent.com/22814355/68380197-53b97880-018a-11ea-9b5e-8e9b475893f1.jpg)

**Comment by linian09** [comment]
华为云账号：hw06587017
测试图片：
![QQ截图20191107220829](https://user-images.githubusercontent.com/57095223/68395707-3f39a800-01ab-11ea-9c3f-02fe13e475f9.png)
中文字符检测结果：
![QQ截图20191107220841](https://user-images.githubusercontent.com/57095223/68395713-419c0200-01ab-11ea-9c8d-b03f1f8deda8.png)

**Comment by Alex20250** [comment]
华为云账号：Alex2025

1、测试图片：
![12](https://user-images.githubusercontent.com/52554168/68449689-240a7f00-0223-11ea-9a31-4304c53eb75f.png)


2、中文字符检测结果：

![13](https://user-images.githubusercontent.com/52554168/68449691-266cd900-0223-11ea-949a-44fcb497f5e8.png)

**Comment by dengleiy** [comment]
华为云账号：hw40732214
1、测试图片
![161](https://user-images.githubusercontent.com/57354648/68475164-54254280-0262-11ea-979c-9a8008e7e738.jpg)
2、中文字符检测结果
![162](https://user-images.githubusercontent.com/57354648/68475176-5c7d7d80-0262-11ea-86cc-49150d6eb874.jpg)

**Comment by hw38169653** [comment]
华为云账号：hw38169653
1、测试图片：
![16 1](https://user-images.githubusercontent.com/57040710/68477258-f267d700-0267-11ea-9def-a498160f7db1.jpg)
2、中文字符检测结果：
![16 2](https://user-images.githubusercontent.com/57040710/68477280-01e72000-0268-11ea-989d-60d985966ff2.jpg)

**Comment by longshenhuigui** [comment]
华为云账号：hw50582000
测试图片：

![C8ZEI`6@~31N5VJ{439TW R](https://user-images.githubusercontent.com/52161158/68484246-de2bd600-0277-11ea-898a-06ffe3d08c7a.png)

中文字符检测结果：
![RKJ@FL%(A0Q`)TFW6L6R7 3](https://user-images.githubusercontent.com/52161158/68484260-e2f08a00-0277-11ea-963e-bc9c3abb8a83.png)

**Comment by Carex-Chunhui** [comment]
华为云账号：hw28207081
测试图片
![image](https://user-images.githubusercontent.com/49952978/68503553-180fd300-029e-11ea-8034-9a92c8148581.png)

**Comment by hw60701982** [comment]
华为云账号：hw60701982
测试图片
![QQ图片20191109165101](https://user-images.githubusercontent.com/57257548/68526227-88f1d200-0314-11ea-92d0-0e10f6427781.png)
中文字符检测结果：
![QQ图片20191109165128](https://user-images.githubusercontent.com/57257548/68526239-a757cd80-0314-11ea-9616-19bb4a80f3ff.png)

**Comment by uflexnihao** [comment]
华为云账号： uflexnihao

测试图片
![1原图](https://user-images.githubusercontent.com/6821672/68526356-da4e9100-0315-11ea-8a92-72954dee9981.PNG)

字符检测结果
![2预测结果](https://user-images.githubusercontent.com/6821672/68526364-e89cad00-0315-11ea-8b2a-e1e539ac8923.PNG)

**Comment by Edward-Wbsz** [comment]
华为云账号： hw28321490
1.测试图片：
[
![VF9V64QFG2JNTKQ78ZCVW10](https://user-images.githubusercontent.com/56443127/68527948-ff4bff80-0327-11ea-9b50-a48e35a50bcd.png)
](url)

2.字符检测结果：
[
![E@N%T6W_ECW9U3 X(5O$OUA](https://user-images.githubusercontent.com/56443127/68527951-096dfe00-0328-11ea-8c37-3bc3c306b27f.png)
](url)

**Comment by chenliang613** [comment]
活动结束，本issue关闭！
