### ISSUE TITLE
（云宝-物体检测）+（Notebook-python人脸识别）

### ISSUE THREAD

**Issue by wjsandy** [huaweicloud/ModelArts-Lab#145]
ID:wjsandy

第一个实验-感觉还是非常快就做完了，因为前期有做关于识别花的实验，群里童学还开玩笑，识别图片大老婆和小老婆 ，我最后做的是识别动物类的！有兴趣可以点进去看看，这节的物体检测涨了一个知识点，导入市场的数据集，这后期用处大一些，废话不多说，特意选了几张图，发现还是不能太相信机器！

![3-1](https://user-images.githubusercontent.com/7964009/60145999-6e520d00-97fa-11e9-9b01-8971ad491d66.png)

然后我用了张老虎和兔子的让预测，也会提示83%，急着写分享，就不用美女图片来预测了！有兴趣的童学可以去试试！这几天太多课了，一会7天，一会微服务，又是云计算，学的天昏地暗！

![3-2](https://user-images.githubusercontent.com/7964009/60146010-76aa4800-97fa-11e9-83fe-c579c005c4e2.png)

第二个Notebook实验来了！按指导一步步复制代码，运行，然后最后在ModelArts-部署上线-上线服务里，上传张人脸图来识别下！会有惊喜，识别完，再操作最后一步删推理资源。特别提一下按需的资源停止没用，要删除哦！昨天3点被计费了！

![3-3](https://user-images.githubusercontent.com/7964009/60146019-7d38bf80-97fa-11e9-8cc9-24aebeb21436.png)
![3-4](https://user-images.githubusercontent.com/7964009/60146026-7f9b1980-97fa-11e9-920e-ce0ef58c4dd3.png)
![3-5](https://user-images.githubusercontent.com/7964009/60146029-86c22780-97fa-11e9-95a5-d6e261b420d3.png)

每日专家答疑，答疑时间为：16：00--17：00 

400元新手资源包免费领：http://t.cn/AiKl9ahM 

本次课程报名学习地址：http://t.cn/AiKjASXh 

每日体验官评选参与：http://t.cn/AiKEnoZL 

实验班活动详情页： https://dwz.cn/RazsyPcy 

完成实验享班级奖励，课程报名截图+实验截图私信云学院小助手
领取抽奖码&开通ModelArts微认证学考资格!

**Comment by chenliang613** [comment]
你好，这个不算扩展案例，请按照第一期（issue 49），第二期（issue 113）的内容，进行扩展。
