### ISSUE TITLE
ModelArts实现零售商客户分群

### ISSUE THREAD

**Issue by wjsandy** [huaweicloud/ModelArts-Lab#146]
*流程：环境搭建（OBS桶、Notbook开发环境-华为ModelArts里都有）-数据同步（市场同步OBS数据集，work目录）-数据导入（导入工具包、导入数据集）

-数据预处理（独热编码、删除相应id列）-K值的选择（导入算法，计算出误差平方各、轮廓系数、根据肘部法则选取适合K值）

-模型构建（循环多次避免局部最优解，得出相对更优模型）-模型使用（聚类分析、预测）-结果可视化（使用matplotlib对预测结果进行可视化显示-点状图）

![4-1](https://user-images.githubusercontent.com/7964009/60148036-1b7c5380-9802-11e9-87ee-fddc4811f1af.png)

1、环境搭建（OBS桶、Notbook开发环境-华为ModelArts里都有）

![4-2](https://user-images.githubusercontent.com/7964009/60148046-28994280-9802-11e9-9c4c-b3bd58d6058d.png)

数据同步（市场同步OBS数据集，work目录）

![4-3](https://user-images.githubusercontent.com/7964009/60148050-2df68d00-9802-11e9-97c9-4d3a1ae1efac.png)

2、数据导入（导入工具包、导入数据集）

![4-4](https://user-images.githubusercontent.com/7964009/60148061-3353d780-9802-11e9-9bde-cb357afa4f83.png)

3、数据预处理（独热编码、删除相应id列）

![4-5](https://user-images.githubusercontent.com/7964009/60148073-3cdd3f80-9802-11e9-9d1a-72d02f9df370.png)

4、K值的选择（导入算法，计算出误差平方各、轮廓系数、根据肘部法则选取适合K值）

![4-6](https://user-images.githubusercontent.com/7964009/60148083-45357a80-9802-11e9-8005-5f64f07c707f.png)
![4-7](https://user-images.githubusercontent.com/7964009/60148091-4a92c500-9802-11e9-83c3-10dc7c898302.png)

5、模型构建（循环多次避免局部最优解，得出相对更优模型）

![4-8](https://user-images.githubusercontent.com/7964009/60148098-5088a600-9802-11e9-8b55-8203bda7cbfb.png)

6、模型使用（聚类分析、预测）

![4-9](https://user-images.githubusercontent.com/7964009/60148108-567e8700-9802-11e9-91af-7d4d7964db1f.png)

7、结果可视化（使用matplotlib对预测结果进行可视化显示-点状图）

​
![4-10](https://user-images.githubusercontent.com/7964009/60148114-5d0cfe80-9802-11e9-847e-e08a257e1e32.png)

**Comment by chenliang613** [comment]
你好，本内容可能不能做为实际应用案例。
