### ISSUE TITLE
打卡

### ISSUE THREAD

**Issue by whrcn** [huaweicloud/ModelArts-Lab#1513]
华为云账号：hw08522247
自动学习案例完成截图
![菊花](https://user-images.githubusercontent.com/57063750/67764893-e0c34a00-fa85-11e9-9d2d-175984001739.png)
![玫瑰花](https://user-images.githubusercontent.com/57063750/67764894-e0c34a00-fa85-11e9-9065-024fc1af1841.png)
![蒲公英](https://user-images.githubusercontent.com/57063750/67764895-e15be080-fa85-11e9-8a75-58719f44e19b.png)
![向日葵](https://user-images.githubusercontent.com/57063750/67764896-e15be080-fa85-11e9-8206-20afe5f31ae9.png)
notebook完成截图
![notebook](https://user-images.githubusercontent.com/57063750/67764953-ff294580-fa85-11e9-837e-cc8bad1b227f.png)

**Comment by chaoxu1203** [comment]
你好，请在 issue #49 下回复，否则无法获得积分
