### ISSUE TITLE
我想问下plot_model函数报这个错误该怎么解决

### ISSUE THREAD

**Issue by s1119858711** [huaweicloud/ModelArts-Lab#1544]
![image](https://user-images.githubusercontent.com/49084147/67858265-c9eb2900-fb53-11e9-9a5e-8347f9e17d7d.png)
 

你好啊 我想问下 这个问题怎么解决呀

**Comment by chaoxu1203** [comment]
请看报错信息，需要在notebook中安装其他依赖包，安装方式见：https://github.com/huaweicloud/ModelArts-Lab/blob/master/docs/faqs.md#%E5%A6%82%E4%BD%95%E5%9C%A8notebook%E4%B8%AD%E5%AE%89%E8%A3%85python%E4%BE%9D%E8%B5%96

**Comment by s1119858711** [comment]
> 请看报错信息，需要在notebook中安装其他依赖包，安装方式见：https://github.com/huaweicloud/ModelArts-Lab/blob/master/docs/faqs.md#%E5%A6%82%E4%BD%95%E5%9C%A8notebook%E4%B8%AD%E5%AE%89%E8%A3%85python%E4%BE%9D%E8%B5%96

好的好的 谢谢啦
