### ISSUE TITLE
`

### ISSUE THREAD

**Issue by meiyoumingzi85** [huaweicloud/ModelArts-Lab#1616]
hw45942105

自动学习案例完成截图：
1. 预测------玫瑰

![玫瑰](https://user-images.githubusercontent.com/57053717/68173289-82322a80-ffb5-11e9-900b-444741a6af26.png)`

2.预测------蒲公英 

![蒲公英](https://user-images.githubusercontent.com/57053717/68173292-83fbee00-ffb5-11e9-9820-253c92c5849d.png)

3预测-------菊花. 

![菊花](https://user-images.githubusercontent.com/57053717/68173297-878f7500-ffb5-11e9-93e1-4885d18382e2.png)

4预测------向日葵. 

![向日葵](https://user-images.githubusercontent.com/57053717/68173298-89593880-ffb5-11e9-989b-c1a9b0d06636.png)

5.Notebook案例完成截图：

![精度](https://user-images.githubusercontent.com/57053717/68173301-8a8a6580-ffb5-11e9-884e-1d5ec4af39b1.png)

_Originally posted by @meiyoumingzi85 in https://github.com/huaweicloud/ModelArts-Lab/issues/49#issuecomment-549634105_

**Comment by chaoxu1203** [comment]
你好，请在#49下面反馈，否则无法获得积分。
