### ISSUE TITLE
华为云账号：hw09792334

### ISSUE THREAD

**Issue by feguyo** [huaweicloud/ModelArts-Lab#1618]
自动学习案例完成截图
![QQ截图20191029093750](https://user-images.githubusercontent.com/57378067/68190974-71031100-ffe9-11e9-9309-2e37b9d6a0a4.png)
![QQ截图20191029093850](https://user-images.githubusercontent.com/57378067/68190976-719ba780-ffe9-11e9-9e1a-492f471e9002.png)
![QQ截图20191029093915](https://user-images.githubusercontent.com/57378067/68190978-72343e00-ffe9-11e9-90e3-d3a75d665f14.png)
![QQ截图20191029093936](https://user-images.githubusercontent.com/57378067/68190980-72ccd480-ffe9-11e9-8ad3-3f338125c143.png)
notebook案例完成截图
![QQ图片20191105104337](https://user-images.githubusercontent.com/57378067/68191024-8b3cef00-ffe9-11e9-9806-63549d8581c8.png)

**Comment by chaoxu1203** [comment]
你好，第一期案例，请在#49下面反馈，否则无法获得积分哦。
