### ISSUE TITLE
通过API上传的物体检测的数据无法被新创建的项目同步

### ISSUE THREAD

**Issue by LiMengyang990726** [huaweicloud/ModelArts-Lab#1619]
1. OBS桶和数据集已经创建并成功上传，格式如下：
```
birds-data
└─── detection
            └─── detection_train
                          └─── a.jpg
                               a.xml
                               b.jpg
                               b.xml
                               ...
```

一个xml的example file如下图所示
![image](https://user-images.githubusercontent.com/34411863/68194704-72840780-fff0-11e9-859f-60affc4560af.png)

2. 目前的问题是，我创建的项目将该数据源作为训练数据集
![image](https://user-images.githubusercontent.com/34411863/68194898-d27aae00-fff0-11e9-8ad1-c2d102a18cd3.png)
可是该数据源有同步失败的错误
![image](https://user-images.githubusercontent.com/34411863/68194977-fdfd9880-fff0-11e9-91d9-fba09fe73047.png)

请问这个问题如何解决？

**Comment by chaoxu1203** [comment]
自动学习导入标注数据的格式是：https://support.huaweicloud.com/exemlug-modelarts/modelarts_21_0009.html。
如果自己无法定位出来，可以提工单咨询后台工程师。

**Comment by LiMengyang990726** [comment]
已经可以了，问题原因是
1. segment放在了size之前，xml的每个tag的顺序必须按照api格式
2. xmin应小于xmax，ymin应小于ymax

**Comment by LiMengyang990726** [comment]
想再请问一下，如果我上传一个文件夹时中断了，再次开启上传的时候之前的文件会被覆盖掉吗？

**Comment by LiMengyang990726** [comment]
以上问题已经解决
