### ISSUE TITLE
系统故障训练任务运行失败

### ISSUE THREAD

**Issue by LiMengyang990726** [huaweicloud/ModelArts-Lab#1643]
在成功同步数据源之后，开始模型训练时出现以下error message
![image](https://user-images.githubusercontent.com/34411863/68445005-983d2680-0213-11ea-8ed9-fb8807e82e3b.png)
请问如何解决

**Comment by chaoxu1203** [comment]
你好，无法根据该错误信息定位问题。可以提华为云工单，让后台工程师帮忙定位并给解决方案。

**Comment by LiMengyang990726** [comment]
已经通过工单解决
