### ISSUE TITLE
<B>Committer(chenliang613)反馈：很好，你的积分已生效！</B>

### ISSUE THREAD

**Issue by 17325223825** [huaweicloud/ModelArts-Lab#1658]
<B>Committer(chenliang613)反馈：很好，你的积分已生效！</B>

华为云账号：liweigu
自动学习案例完成截图：
![1](https://user-images.githubusercontent.com/31612697/59538129-55f50f00-8f2b-11e9-8c56-f4773dfef9ef.jpg)
![2](https://user-images.githubusercontent.com/31612697/59538131-55f50f00-8f2b-11e9-8f4f-3a3e196e5e40.jpg)
![3](https://user-images.githubusercontent.com/31612697/59538132-568da580-8f2b-11e9-8504-e8f5c5ca5701.jpg)
![4](https://user-images.githubusercontent.com/31612697/59538133-568da580-8f2b-11e9-82af-b48a0df026db.jpg)

Notebook案例完成截图：
![5](https://user-images.githubusercontent.com/31612697/59538140-5b525980-8f2b-11e9-97c9-978df2bac954.jpg)

_Originally posted by @liweigu in https://github.com/huaweicloud/ModelArts-Lab/issues/49#issuecomment-502262658_

**Comment by chenliang613** [comment]
@17325223825  请问这是？
