### ISSUE TITLE
模型导出到本地，用tfs运行后，对应的client API，可有文档？

### ISSUE THREAD

**Issue by qipeizhen** [huaweicloud/ModelArts-Lab#1702]
![图片](https://user-images.githubusercontent.com/18319258/71236451-fcd2c180-2339-11ea-824d-18c6f63a5ef8.png)

**Comment by qipeizhen** [comment]
`docker run --name ai -p 8500:8500 -p 8501:8501 -v /model/retinanet:/models/retinanet -v /model/retinanet/models.config:/models/models.config -t tensorflow/serving --model_config_file=/models/models.config`

**Comment by chaoxu1203** [comment]
tensorflow serving 的API，可以去tensorflow 官网查看

**Comment by qipeizhen** [comment]
`"""
Client side code to perform a single API call to a tensorflow model up and running.
"""
import argparse
import json

import numpy as np
import requests
from object_detection.utils import visualization_utils as vis_util
from object_detection.utils import plot_util
from object_detection.utils import label_map_util
import object_detection.utils.ops as utils_ops
from PIL import Image

EPS = np.finfo(float).eps

def format_mask(detection_masks, detection_boxes, N, image_size):
    """
    Format the m*m detection soft masks as full size binary masks. 

    Args:
        detection_masks (np.array): of size N * m * m
        detection_boxes (np.array): of size N * 4 with the normalized bow coordinates.
            Coordinates are written as [y_min, x_min, y_max, x_max]
        N (int): number of detections in the image
        image_size (tuple(int))

    Returns:
        detection_masks (np.array): of size N * H * W  where H and W are the image Height and Width.

    """
    (height, width, _) = image_size
    output_masks = np.zeros((N, image_size[0], image_size[1]))
    # Process the masks related to the N objects detected in the image
    for i in range(N):
        normalized_mask = detection_masks[i].astype(np.float32)
        normalized_mask = Image.fromarray(normalized_mask, 'F')

        # Boxes are expressed with 4 scalars - normalized coordinates [y_min, x_min, y_max, x_max]
        [y_min, x_min, y_max, x_max] = detection_boxes[i]

        # Compute absolute boundary of box
        box_size = (int((x_max - x_min) * width), int((y_max - y_min) * height)) 

        # Resize the mask to the box size using LANCZOS appoximation
        resized_mask = normalized_mask.resize(box_size, Image.LANCZOS)

        # Convert back to array
        resized_mask = np.array(resized_mask).astype(np.float32)

        # Binarize the image by using a fixed threshold
        binary_mask_box = np.zeros(resized_mask.shape)
        thresh = 0.5
        (h, w) = resized_mask.shape

        for k in range(h):
            for j in range(w):
                if resized_mask[k][j] >= thresh:
                    binary_mask_box[k][j] = 1

        binary_mask_box = binary_mask_box.astype(np.uint8)

        # Replace the mask in the context of the original image size
        binary_mask = np.zeros((height, width))

        x_min_at_scale = int(x_min * width)
        y_min_at_scale = int(y_min * height)

        d_x = int((x_max - x_min) * width)
        d_y = int((y_max - y_min) * height)

        for x in range(d_x):
            for y in range(d_y):
                binary_mask[y_min_at_scale + y][x_min_at_scale + x] = binary_mask_box[y][x] 

        # Update the masks array
        output_masks[i][:][:] = binary_mask

    # Cast mask as integer
    output_masks = output_masks.astype(np.uint8)
    return output_masks

def load_image_into_numpy_array(image):
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape((im_height, im_width, 3)).astype(np.float32)
  #return np.asarray(image, dtype=np.float32)


def pre_process(image_path):
    """
    Pre-process the input image to return a json to pass to the tf model

    Args:
        image_path (str):  Path to the jpeg image

    Returns:
        formatted_json_input (str)
    """

    image = Image.open(image_path).convert("RGB")
    # (im_width, im_height) = image.size
    # image = np.asarray(image, dtype=np.float32) / 255.
    # image = image[np.newaxis, :, :, :]
    # print(image.shape)

    image_np = load_image_into_numpy_array(image)
    # Expand dims to create  bach of size 1
    image_tensor = np.expand_dims(image_np, 0)
    print(image_tensor.shape)
    #formatted_json_input = json.dumps({"signature_name": "predict_object", "instances": [{'images': image_tensor.tolist()}]})
    formatted_json_input = json.dumps({"signature_name": "predict_object", "instances": image_tensor.tolist()})

    return formatted_json_input


def post_process(server_response, image_size):
    """
    Post-process the server response

    Args:
        server_response (requests.Response)
        image_size (tuple(int))

    Returns:
        post_processed_data (dict)
    """
    data = json.loads(server_response.text)
    num_boxes = len(data['detection_classes'])
    labels_list = ['box','cell','imei','time','cert']
    classes = []
    boxes = []
    scores = []
    prob_threshold = 0.3
    result_return = dict()
    for i in range(num_boxes):
      if data['detection_scores'][i] > prob_threshold:
        class_id = data['detection_classes'][i] - 1
        classes.append(labels_list[int(class_id)])
        boxes.append(data['detection_boxes'][i])
        scores.append(data['detection_scores'][i])
    ##########add NMS#######################################
    nms_iou_threshold = 0.3
    bounding_boxes = boxes
    confidence_score = scores
    # Bounding boxes
    boxes = np.array(bounding_boxes)
    picked_boxes = []
    picked_score = []
    picked_classes = []
    if len(boxes) != 0:
      # coordinates of bounding boxes
      start_x = boxes[:, 0]
      start_y = boxes[:, 1]
      end_x = boxes[:, 2]
      end_y = boxes[:, 3]
      # Confidence scores of bounding boxes
      score = np.array(confidence_score)
      # Picked bounding boxes
      # Compute areas of bounding boxes
      areas = (end_x - start_x + 1) * (end_y - start_y + 1)
      # Sort by confidence score of bounding boxes
      order = np.argsort(score)
      # Iterate bounding boxes
      while order.size > 0:
        # The index of largest confidence score
        index = order[-1]
        # Pick the bounding box with largest confidence score
        picked_boxes.append(bounding_boxes[index])
        picked_score.append(confidence_score[index])
        picked_classes.append(classes[index])
        # Compute ordinates of intersection-over-union(IOU)
        x1 = np.maximum(start_x[index], start_x[order[:-1]])
        x2 = np.minimum(end_x[index], end_x[order[:-1]])
        y1 = np.maximum(start_y[index], start_y[order[:-1]])
        y2 = np.minimum(end_y[index], end_y[order[:-1]])
        # Compute areas of intersection-over-union
        w = np.maximum(0.0, x2 - x1 + 1)
        h = np.maximum(0.0, y2 - y1 + 1)
        intersection = w * h
        # Compute the ratio between intersection and union
        ratio = intersection / (areas[index] + areas[order[:-1]] - intersection + EPS)
        left = np.where(ratio < nms_iou_threshold)
        order = order[left]

    result_return['detection_classes'] = picked_classes
    result_return['detection_boxes'] = picked_boxes
    result_return['detection_scores'] = picked_score
    return result_return


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Performs call to the tensorflow-serving REST API.')
    parser.add_argument('--server_url', dest='server_url', type=str, required=True,
                        help='URL of the tensorflow-serving accepting API call. '
                             'e.g. http://localhost:8501/v1/models/omr_500:predict')
    parser.add_argument('--image_path', dest='image_path', type=str,
                        help='Path to the jpeg image')
    parser.add_argument('--output_json', dest='output_json', type=str, default='tf_output.json',
                        help='Path to the output json file resulting from the API call')
    parser.add_argument('--save_output_image', dest='save_output_image', type=bool, default=False,
                        help='Whether the output_image should be built from the predictions')
    parser.add_argument('--label_map', dest='label_map', type=str, default="mapping_all_classes.txt",
                        help='Path to the label map, which is json-file that maps each category name '
                             'to a unique number.')
    args = parser.parse_args()

    # Map args to var
    server_url = args.server_url
    image_path = args.image_path
    output_image = args.output_json
    save_output_image = args.save_output_image
    path_to_labels = args.label_map

    # Build input data
    print(f'\n\nPre-processing input file {image_path}...\n')
    formatted_json_input = pre_process(image_path)
    print('Pre-processing done! \n')

    # Call tensorflow server
    headers = {"content-type": "application/json"}
    print(f'\n\nMaking request to {server_url}...\n')
    server_response = requests.post(server_url, data=formatted_json_input, headers=headers)
    print(f'Request returned\n')
    print(json.loads(server_response.text))
    # Post process output
    print(f'\n\nPost-processing server response...\n')
    image = Image.open(image_path).convert("RGB")
    image_np = load_image_into_numpy_array(image)
    output_dict = post_process(server_response, image_np.shape)
    print(f'Post-processing done!\n')

    # Save output on disk
    print(f'\n\nSaving output to {output_image}\n\n')
    with open(output_image, 'w+') as outfile:
        json.dump(json.loads(server_response.text), outfile)
    print(f'Output saved!\n')

    if save_output_image:
        # Save output on disk
        category_index = label_map_util.create_category_index_from_labelmap(path_to_labels, use_display_name=True)

        # Visualization of the results of a detection.
        vis_util.visualize_boxes_and_labels_on_image_array(
            image_np,
            output_dict['detection_boxes'],
            output_dict['detection_classes'],
            output_dict['detection_scores'],
            category_index,
            instance_masks=output_dict.get('detection_masks'),
            use_normalized_coordinates=True,
            line_thickness=8,
            )
        output_with_no_extension = output_image.split('.', 1)[0]
        output_image = ''.join([output_with_no_extension, '.jpeg'])
        Image.fromarray(image_np).save(output_image)
        print('\n\nImage saved\n\n')
`

**Comment by qipeizhen** [comment]
![图片](https://user-images.githubusercontent.com/18319258/71352124-63611500-25b0-11ea-925f-1082ae5cd278.png)

**Comment by qipeizhen** [comment]
麻烦大佬帮忙看一下，为什么会报错Tensor name: threshold has inconsistent batch size: 1 expecting: 100

**Comment by qipeizhen** [comment]
https://blog.csdn.net/JerryZhang__/article/details/88540156  rest API 不支持？
