### ISSUE TITLE
【2019-05-26】NLP自然语言处理，NER命名实体识别应用实践

### ISSUE THREAD

**Issue by JinhengZhang** [huaweicloud/ModelArts-Lab#20]
本案例默认您已经练习过“手写数字图像识别应用实践”https://github.com/huaweicloud/ModelArts-Lab/issues/1 ，不熟悉ModelArts的朋友请先花点时间熟悉ModelArts起手式。

实践1：按照下面步骤完成Notebook环境数据准备、模型训练、模型测试：
https://github.com/huaweicloud/ModelArts-Lab/tree/master/%E7%BB%BC%E5%90%88AI%E5%BC%80%E5%8F%91%E6%A1%88%E4%BE%8B/NER-BERT

实践2：ModelArts 训练服务&模型部署：NLP（自然语言处理） NER（命名实体识别）应用端到端实验：
下周放出敬请期待，欢迎您根据实践1提出自己的期望，我们会尽量在后续的实践中迭代完善。更加欢迎给我们提交Issues&PR 让我们共同进步。

**Comment by chenliang613** [comment]
本社区第二个实践

**Comment by benmcq2019** [comment]
按着步奏完成实践，在开始两步压缩包里面的内容有些变化外，其它完全一致。在第12步（在训练集上进行训练）会花费比较长的时间，切记不要关闭页面。
![微信图片_20190527210640](https://user-images.githubusercontent.com/46392381/58421997-0659bb00-80c4-11e9-8a7d-da09c796e3f5.png)成功后就调戏它吧！！！

**Comment by benmcq2019** [comment]
本实践的开始环境要求为10G以上EVS配置。但目前华为云提供的EVS有个5G以上
![image](https://user-images.githubusercontent.com/46392381/58427225-9ce0a900-80d1-11e9-9afb-dc2fba471606.png)这个条款！所以，在运行结束后，酌情考虑是否继续扣费！

**Comment by JinhengZhang** [comment]
> 按着步奏完成实践，在开始两步压缩包里面的内容有些变化外，其它完全一致。在第12步（在训练集上进行训练）会花费比较长的时间，切记不要关闭页面。
> ![微信图片_20190527210640](https://user-images.githubusercontent.com/46392381/58421997-0659bb00-80c4-11e9-8a7d-da09c796e3f5.png)成功后就调戏它吧！！！
> 最后记得关闭开发环境

关于Organization和Location的区分也是现在命名实体识别中的一个一个研究难点。可以适当调参来调整模型精度，如增大batch_size和num_train_epochs ~

**Comment by JinhengZhang** [comment]
> 本实践的开始环境要求为10G以上EVS配置。但目前华为云提供的EVS有个5G以上
> ![image](https://user-images.githubusercontent.com/46392381/58427225-9ce0a900-80d1-11e9-9afb-dc2fba471606.png)这个条款！所以，在运行结束后，酌情考虑是否继续扣费！

由于BERT模型需要配置空间较大，本实践项目至少需要7G的配置环境，感谢提醒~

**Comment by fivestarsky** [comment]
@JinhengZhang  关键点都提示的好详细。

**Comment by fivestarsky** [comment]
@benmcq2019  后续的example 更有可戏性哈

**Comment by benmcq2019** [comment]
@fivestarsky 期待233333

**Comment by amy-309** [comment]
@JinhengZhang 按照老师给的实践步骤，一步步完成了，学习到了什么是NER。
一个小建议，添加一条提醒：开发者在完成实践后，要及时删除notebook，以免产生计费。
注：停止notebook还不行，因为用了10G EVS。

**Comment by JinhengZhang** [comment]
> @JinhengZhang 按照老师给的实践步骤，一步步完成了，学习到了什么是NER。
> 一个小建议，添加一条提醒：开发者在完成实践后，要及时删除notebook，以免产生计费。
> 注：停止notebook还不行，因为用了10G EVS。

非常感谢提醒，稍后会添加！多多交流~

**Comment by chenliang613** [comment]
> 本社区第二个实践
