### ISSUE TITLE
调参提高猫狗识别精确度至85.5%

### ISSUE THREAD

**Issue by ilovescrapy** [huaweicloud/ModelArts-Lab#221]
基于第二期提高精确率的第一种思路，通过修改max_epochs, learning_rate,patch_size,提高精确度。
定两参调一参的方式进行调节。
下面是部分调节参数过程中尝试过的几个数据
![Screenshot_2019-07-03-21-51-45-54](https://user-images.githubusercontent.com/49826390/60631265-45043300-9e31-11e9-89e7-0e74605c6a1b.png)
![Screenshot_2019-07-03-22-11-01-03](https://user-images.githubusercontent.com/49826390/60631267-4afa1400-9e31-11e9-826d-edabed8acb22.png)
![Screenshot_2019-07-03-22-23-54-73](https://user-images.githubusercontent.com/49826390/60631268-4fbec800-9e31-11e9-8a73-5909920913c6.png)
![Screenshot_2019-07-03-22-53-12-89](https://user-images.githubusercontent.com/49826390/60631274-53eae580-9e31-11e9-9743-ede3c3eb6ffc.png)
观察发现,learing_rate参数的修改对于精确度的影响是比较大的。发现learning_rate为ne-5时的精确度很难达到80%以上。发现该参数最佳范围在3e-4附近。
patch_size通过实验发现它的越大精确度越高，但达到一定数值影响并不大。
max_epochs此值达到几十精确度就可以达到该参上限。
下面是参数达到比较适合数值时的实验数据。
![Screenshot_2019-07-03-22-55-23-79](https://user-images.githubusercontent.com/49826390/60631565-9c56d300-9e32-11e9-9875-3bf20cc75c5f.png)
![Screenshot_2019-07-03-22-55-51-57](https://user-images.githubusercontent.com/49826390/60631567-9eb92d00-9e32-11e9-954c-525325f43b82.png)

**Comment by chaoxu1203** [comment]
感谢分享。精度超过84%，可以额外获得一个积分。

**Comment by chenliang613** [comment]
+1
