### ISSUE TITLE
ModelArts 自学打卡

### ISSUE THREAD

**Issue by PsyduckLiu** [huaweicloud/ModelArts-Lab#256]
华为云账号：HaolinLiu

自动学习案例完成截图：

![玫瑰效果图](https://user-images.githubusercontent.com/42675201/60736400-69732300-9f89-11e9-9b0e-c88712c2a0d4.PNG)
![雏菊效果图](https://user-images.githubusercontent.com/42675201/60736403-6ed06d80-9f89-11e9-8fcf-8495848e97f7.PNG)
![蒲公英效果图](https://user-images.githubusercontent.com/42675201/60736411-742db800-9f89-11e9-9f21-bebda2ae41d5.PNG)
![向日葵效果图](https://user-images.githubusercontent.com/42675201/60736413-77c13f00-9f89-11e9-818b-2a2038461d8e.PNG)

Notebook案例完成截图：

![实践效果](https://user-images.githubusercontent.com/42675201/60736425-827bd400-9f89-11e9-8278-a2649356c7bd.PNG)

**Comment by chenliang613** [comment]
你好，请按照规则，统一在issue 49里跟帖回复，才能获得积分哦。
