### ISSUE TITLE
ModelArts图像分类实践

### ISSUE THREAD

**Issue by Jugr** [huaweicloud/ModelArts-Lab#260]

**Comment by Mr-Super** [comment]
华为云账号：Mr__White
自动学习案例完成截图：
![微信截图_20190706105545](https://user-images.githubusercontent.com/21274476/60750957-e500be80-9fe1-11e9-9343-f32c194953b2.png)
![微信截图_20190706105718](https://user-images.githubusercontent.com/21274476/60750958-e7631880-9fe1-11e9-9065-b37d941d0267.png)
Notebook案例完成截图：
![cat1](https://user-images.githubusercontent.com/21274476/60750980-111c3f80-9fe2-11e9-997a-b7af5a37999a.png)
![cat2](https://user-images.githubusercontent.com/21274476/60750982-124d6c80-9fe2-11e9-8142-0a136c00ed46.png)
