### ISSUE TITLE
训练模型总运行失败的一个原因

### ISSUE THREAD

**Issue by simistar** [huaweicloud/ModelArts-Lab#3]
下载train_mnist.py文件要当心，因为如果直接点击右键进行“另存为”时，下载下来的文件可能已经变为了一个网页文件（虽然train_mnist.py点击属性时显示仍然是pathon file），但在创建训练后，就会一直初始化，并且这时日志中会出现提示“SyntsxError”。
解决方法：我的方法可能有些笨，但可以解决问题，分享一下：用notepad++将train_mnist.py打开，并比对着github中打开的源文件，将你下载的train_mnist.py中增加的内容删除（注意一般是在头部和尾部都有多出来的内容），再另存一份新的train_mnist.py。使用这个新的train_mnist.py作为启动文件再进行训练，应该就可以了。

**Comment by chenliang613** [comment]
Thanks for sharing

**Comment by wonleing** [comment]
or you can just download related files here: http://123.206.26.34/html/ai/
