### ISSUE TITLE
[讨论]notebook创建过程中Tensoflow1.31.1(python)引擎造成TimeOutError

### ISSUE THREAD

**Issue by merria28** [huaweicloud/ModelArts-Lab#333]
在第三期，模型调优与网络参数中，对于03任务出现如下错误：
![image](https://user-images.githubusercontent.com/29765699/60953866-93816800-a330-11e9-92c2-5c1cb3fc600c.png)

最后消除该问题的办法是：重新创建notebook，选择引擎为Tensorflow，而非推荐的多引擎。

那么问题来了，
在我第一次运行03任务时，选择的是多引擎下的Tensorflow1.31.1；第二次运行直接使用的是Tensorflow引擎。 这两个有什么不同？都是简单的加载VGG16模型。
Tensorflow1.31.1下，多加了一个imagenet权重就出错了

**Comment by qian-zh** [comment]
你好，在多引擎Tensorflow1.13.1中，当前这个命令的执行与下载是没有问题的，不清楚是否你当时网络情况是否有抖动，或者这个问题现在还能重现吗。
![20190715-091334(eSpace)](https://user-images.githubusercontent.com/3394707/61191789-e7010680-a6e0-11e9-9e6f-38ed26905057.png)

**Comment by chaoxu1203** [comment]
还是推荐使用多引擎中的TensorFlow，超时应该是当时网络拥堵造成的

**Comment by merria28** [comment]
@qian-zh  我在最新的实战中，使用多引擎Tensorflow1.13.1未出现TimeOut。很有可能是你说的网络抖动造成的。

**Comment by merria28** [comment]
@chaoxu1203  这个方法好，以后碰见类似的问题就可以参照这个标准执行，感谢。
