### ISSUE TITLE
ModelArts 不显示 OBS

### ISSUE THREAD

**Issue by louxy126** [huaweicloud/ModelArts-Lab#338]
想在Modelarts中使用obs里的图像进行物体检测，但是在创建物体检测项目中选择obs路径时，一个obs都不显示，密钥已经添加过了。

**Comment by ilovescrapy** [comment]
obs创建了吗，请不要在这提问，有任何疑问请在群里提问，如果没有加群请添加：hwyeiqyzn

**Comment by louxy126** [comment]
是因为目前只支持北京的节点，在其他节点建的桶都显示不出来…………

**Comment by chenliang613** [comment]
@louxy126  对的，ModelArts选择的region（北京一、北京四）和OBS存储数据的region，需要保持一致。

**Comment by chaoxu1203** [comment]
此Issue关闭
