### ISSUE TITLE
【讨论】三种算法合用提高猫狗识别精确度

### ISSUE THREAD

**Issue by ilovescrapy** [huaweicloud/ModelArts-Lab#380]
之前在网上有看到猫狗大战使用VGG16算法，resnet50算法和xception算法来提高识别率并成功获得top2排名，我想将这个方法应用到第一二期猫狗识别中不知道应该如何实现希望大佬们能提供些思路

**Comment by ilovescrapy** [comment]
文章所在的链接https://ypw.io/dogs-vs-cats-2/

**Comment by chaoxu1203** [comment]
建议这种讨论的issue，加上【讨论】前缀。这样可以吸引其他的开发者进来一起讨论
