### ISSUE TITLE
手写数字识别模型训练问题总结

### ISSUE THREAD

**Issue by leewishyuanfang** [huaweicloud/ModelArts-Lab#4]
经过一个多小时的尝试，终于成功训练并测试了手写数字识别模型，现在总结一下自己在尝试过程中遇到的一些问题：
1. 关于train_mnist.py的下载，正如其他人测试过的，这个文件通过右键另存为，下载回来的内容是html网页。我本人倾向于在pycharm中新建一个python文件，然后把train_mnist.py的代码直接复制到这个文件中，再把这个python文件上传。这样做的好处在于pycharm会自动检测python代码中存在的静态错误，特别是在python中是使用相同数目的行首缩进空格来划分代码块的，程序中行首缩进空格的错误很容易就被忽略了（我在复制代码时就出现了最后一行代码的行首缩进空格全没了的情况，还是通过pycharm发现的）。
2. 在部署模型时，需要先将推理代码customize_service.py和配置文件config.json 上传，切记切记是上传到/mnist-example/log/model/目录下，我一开始就是想当然了，python格式的文件都上传到了/mnist-example/codes/目录下了，导致模型的部署没问题，发布运行也没问题，但在预测时，预测界面没有出来图像上传的组件，通过查找原因，发现是部署时程序没能找到config.json文件，而自动生成了一个默认的配置文件的缘故。重新上传推理代码customize_service.py和配置文件config.json 后，问题得到了解决。

**Comment by chenliang613** [comment]
感谢分享，很好的总结！

**Comment by huxian123** [comment]
华为云账号 huxian123
手写数字识别
![tensorboard](https://user-images.githubusercontent.com/14010658/61842416-aa948e00-aeca-11e9-9abd-e511929c0e72.jpg)
![手写数字识别](https://user-images.githubusercontent.com/14010658/61842418-acf6e800-aeca-11e9-9f91-c89656cb6594.jpg)
