### ISSUE TITLE
blueking

### ISSUE THREAD

**Issue by A-k-ing** [huaweicloud/ModelArts-Lab#439]
华为云账号：blueking

自动学习案例完成截图：
![QQ浏览器截图20190721183329](https://user-images.githubusercontent.com/12869383/61590603-78dfa680-abee-11e9-8fab-5b5c313ffd72.png)
![QQ浏览器截图20190721183200](https://user-images.githubusercontent.com/12869383/61590604-7f6e1e00-abee-11e9-865a-1552142973f0.png)
![QQ浏览器截图20190721183210](https://user-images.githubusercontent.com/12869383/61590605-8563ff00-abee-11e9-94b7-da6fc6a04fb4.png)
![QQ浏览器截图20190721183306](https://user-images.githubusercontent.com/12869383/61590609-8dbc3a00-abee-11e9-97df-95042902abf2.png)
![QQ浏览器截图20190721183234](https://user-images.githubusercontent.com/12869383/61590614-944ab180-abee-11e9-91db-062fc578a16e.png)

Notebook案例完成截图：
![QQ浏览器截图20190721192608](https://user-images.githubusercontent.com/12869383/61590617-96ad0b80-abee-11e9-84f9-3cebed3c7b87.png)

**Comment by JinhengZhang** [comment]
请咋issue#49中跟帖回复，谢谢。
