### ISSUE TITLE
这么烂的反馈，是怎么做到的？

### ISSUE THREAD

**Issue by liu09114** [huaweicloud/ModelArts-Lab#446]
![image](https://user-images.githubusercontent.com/15519590/61617312-0548a280-ac9d-11e9-90b2-c85c288b2536.png)
刷新半天不出结果，我哪知道管理员是谁，去哪找？

**Comment by liu09114** [comment]
![image](https://user-images.githubusercontent.com/15519590/61617416-3a54f500-ac9d-11e9-8e88-74ef2e4a7888.png)

**Comment by chaoxu1203** [comment]
你好，感谢反馈。我们已经将这个报错信息的优化纳入计划了，后面会提供更加友好的提示信息。

**Comment by benmcq2019** [comment]
咦，我今天也是出现这样的界面了！我是运行了太多造成了。后来删除了些就好了！

**Comment by chenliang613** [comment]
@liu09114 请聚焦问题本身的讨论和反馈。

**Comment by liu09114** [comment]
我不是运行了太多，就运行了一个，就刷不出来

**Comment by chenliang613** [comment]
@liu09114  issue问题的标题，请描述问题本身，如：错误日志反馈不合理等
