### ISSUE TITLE
华为云账号：w65565

### ISSUE THREAD

**Issue by w65565** [huaweicloud/ModelArts-Lab#463]
华为云账号：w65565

自动学习案例完成截图：
![image](https://user-images.githubusercontent.com/41976678/61729832-b38e3e00-adaa-11e9-89de-1f58d2dfa484.png)

![image](https://user-images.githubusercontent.com/41976678/61729869-c99bfe80-adaa-11e9-977a-060ee0b52c89.png)

![image](https://user-images.githubusercontent.com/41976678/61729881-ce60b280-adaa-11e9-9b07-c09f04f7a9b8.png)

![image](https://user-images.githubusercontent.com/41976678/61729890-d28cd000-adaa-11e9-8205-d99df1667c69.png)

Notebook案例完成截图：
![image](https://user-images.githubusercontent.com/41976678/61729904-d882b100-adaa-11e9-9c65-3f84a54c45d3.png)

_Originally posted by @w65565 in https://github.com/huaweicloud/ModelArts-Lab/issues/49#issuecomment-514287516_

**Comment by JinhengZhang** [comment]
已在issue中跟帖，本issue关闭
