### ISSUE TITLE
【华为云ModelArts-Lab AI实战营】第一期：图像分类 (I)

### ISSUE THREAD

**Issue by NightExp** [huaweicloud/ModelArts-Lab#467]
华为云账号：NightEzp

自动学习案例完成截图：

![1](https://user-images.githubusercontent.com/26305246/61759413-f0822100-adfa-11e9-8b66-bd334635e9ef.png)
![2](https://user-images.githubusercontent.com/26305246/61759414-f0822100-adfa-11e9-996d-2cf5f8672ba4.png)
![3](https://user-images.githubusercontent.com/26305246/61759415-f0822100-adfa-11e9-9d4d-c4a7468e2a31.png)
![4](https://user-images.githubusercontent.com/26305246/61759416-f11ab780-adfa-11e9-9c51-e27ccea2b804.png)
![QQ截图20190724100309](https://user-images.githubusercontent.com/26305246/61759428-f841c580-adfa-11e9-9e89-74fa3c72a0b7.png)

**Comment by chaoxu1203** [comment]
你好，请在[第一期](https://github.com/huaweicloud/ModelArts-Lab/issues/49)的issue底下反馈，否则无法获得积分的哦。

**Comment by chaoxu1203** [comment]
你这issue我会关闭掉，否则会干扰其他开发者的。
