### ISSUE TITLE
blueking

### ISSUE THREAD

**Issue by A-k-ing** [huaweicloud/ModelArts-Lab#486]
华为云账号：blueking
自动学习案例完成截图：
![QQ浏览器截图20190721183200](https://user-images.githubusercontent.com/12869383/61842338-5f7a7b00-aeca-11e9-9b2c-3a81b9bc2af5.png)
![QQ浏览器截图20190721183234](https://user-images.githubusercontent.com/12869383/61842345-630e0200-aeca-11e9-8df6-001a5382083f.png)
![QQ浏览器截图20190721183306](https://user-images.githubusercontent.com/12869383/61842349-6608f280-aeca-11e9-84f8-4e5011e43569.png)
![QQ浏览器截图20190721183329](https://user-images.githubusercontent.com/12869383/61842357-6b663d00-aeca-11e9-97b2-7d3cae8cbb09.png)
![QQ浏览器截图20190721192608](https://user-images.githubusercontent.com/12869383/61842359-6e612d80-aeca-11e9-8009-12bb5b6a6887.png)

**Comment by JinhengZhang** [comment]
请在实战营对应issue后跟帖
