### ISSUE TITLE
手写数字案例实现

### ISSUE THREAD

**Issue by fjqsun** [huaweicloud/ModelArts-Lab#514]
![0000](https://user-images.githubusercontent.com/51841701/61956283-5df6a300-afef-11e9-903a-10757ce67511.JPG)
![选错了怎么改](https://user-images.githubusercontent.com/51841701/61956294-6222c080-afef-11e9-914f-9a3421689a49.JPG)
<img width="275" alt="1111" src="https://user-images.githubusercontent.com/51841701/61956293-60f19380-afef-11e9-8739-b27fd89e284a.png">
![5](https://user-images.githubusercontent.com/51841701/61956289-5f27d000-afef-11e9-8379-440901bb611e.JPG)
![4](https://user-images.githubusercontent.com/51841701/61956288-5e8f3980-afef-11e9-8427-b5a23956f2ef.JPG)
![6](https://user-images.githubusercontent.com/51841701/61956290-5f27d000-afef-11e9-9d8e-e07d45e2d3d5.JPG)

**Comment by chaoxu1203** [comment]
你好，该分享只是将手写数字识别的代码在notebook中运行了一遍，无法获得积分哦。期待你分享更加有价值的AI实践心得，请参考社区的[积分规则](https://github.com/huaweicloud/ModelArts-Lab/tree/master/merit_rank#%E7%A7%AF%E5%88%86%E8%A7%84%E5%88%99)。
