### ISSUE TITLE
自动学习案例1

### ISSUE THREAD

**Issue by fengtumo** [huaweicloud/ModelArts-Lab#528]
华为云账号 fengtumo

- 

![Snipaste_2019-07-28_17-02-57](https://user-images.githubusercontent.com/53395065/62004720-3c1a2f00-b15b-11e9-9edb-08efbe2f9cd2.png)

**Comment by chaoxu1203** [comment]
你好，第一期的完成结果请到[第一期的issue](https://github.com/huaweicloud/ModelArts-Lab/issues/49)底下回复哦，否则无法获得积分
