### ISSUE TITLE
案例二

### ISSUE THREAD

**Issue by Bourne-M** [huaweicloud/ModelArts-Lab#529]
华为云账号：Bourne-M
**智能标注完成截图：**
![2-1](https://user-images.githubusercontent.com/13611481/62005595-37a84300-b168-11e9-9150-045c255a0df9.png)

![2-2-1](https://user-images.githubusercontent.com/13611481/62005597-3840d980-b168-11e9-9535-c94d6c021658.png)
**模型训练完成截图：**
![2-2](https://user-images.githubusercontent.com/13611481/62005596-37a84300-b168-11e9-95e8-d08c4e7952d4.png)
**部署模型完成截图：**
![2-3](https://user-images.githubusercontent.com/13611481/62005598-3840d980-b168-11e9-8e29-da4aa0a3b1f2.png)
![2-4](https://user-images.githubusercontent.com/13611481/62005599-3840d980-b168-11e9-88e7-f33cae1ff6a4.png)

**Comment by JinhengZhang** [comment]
你好，完成实战营案例请在对应issue后跟帖，当前新开issue格式有误。

**Comment by Bourne-M** [comment]
华为云账号：Bourne-M
**智能标注完成截图：**
![2-1](https://user-images.githubusercontent.com/13611481/62005595-37a84300-b168-11e9-9150-045c255a0df9.png)

![2-2-1](https://user-images.githubusercontent.com/13611481/62005597-3840d980-b168-11e9-9535-c94d6c021658.png)
**模型训练完成截图：**
![2-2](https://user-images.githubusercontent.com/13611481/62005596-37a84300-b168-11e9-95e8-d08c4e7952d4.png)
**部署模型完成截图：**
![2-3](https://user-images.githubusercontent.com/13611481/62005598-3840d980-b168-11e9-8e29-da4aa0a3b1f2.png)
![2-4](https://user-images.githubusercontent.com/13611481/62005599-3840d980-b168-11e9-88e7-f33cae1ff6a4.png)
