### ISSUE TITLE
第一期

### ISSUE THREAD

**Issue by Bourne-M** [huaweicloud/ModelArts-Lab#530]
华为云账号：Bourne-M
**自动学习案例完成截图：**
![微信截图_20190727193501](https://user-images.githubusercontent.com/13611481/62005868-016cc280-b16c-11e9-80a0-e572d16240e4.png)
![微信截图_20190727193522](https://user-images.githubusercontent.com/13611481/62005869-016cc280-b16c-11e9-8809-5e7e99555842.png)
![微信截图_20190727193540](https://user-images.githubusercontent.com/13611481/62005870-02055900-b16c-11e9-87b2-677c87b0cdb5.png)
![微信截图_20190727193601](https://user-images.githubusercontent.com/13611481/62005871-02055900-b16c-11e9-8379-9ed4d4750cc2.png)
**Notebook案例完成截图：**
![1-5](https://user-images.githubusercontent.com/13611481/62005874-15182900-b16c-11e9-99ef-9e1f2446ca7e.png)

**Comment by JinhengZhang** [comment]
你好，完成实战营案例请在对应issue后跟帖，当前新开issue格式有误。

**Comment by Bourne-M** [comment]
华为云账号：Bourne-M
**自动学习案例完成截图：**
![微信截图_20190727193501](https://user-images.githubusercontent.com/13611481/62005868-016cc280-b16c-11e9-80a0-e572d16240e4.png)
![微信截图_20190727193522](https://user-images.githubusercontent.com/13611481/62005869-016cc280-b16c-11e9-8809-5e7e99555842.png)
![微信截图_20190727193540](https://user-images.githubusercontent.com/13611481/62005870-02055900-b16c-11e9-87b2-677c87b0cdb5.png)
![微信截图_20190727193601](https://user-images.githubusercontent.com/13611481/62005871-02055900-b16c-11e9-8379-9ed4d4750cc2.png)
**Notebook案例完成截图：**
![1-5](https://user-images.githubusercontent.com/13611481/62005874-15182900-b16c-11e9-99ef-9e1f2446ca7e.png)
