### ISSUE TITLE
在ModelArts上提交的训练跑到中途会卡住

### ISSUE THREAD

**Issue by janer0** [huaweicloud/ModelArts-Lab#63]
提交的训练显示正在运行，但是日志不再更新，obs上的log更新时间也不动了，资源占用也变为0%，log没有任何报错，就是到某个时间突然不动了。
之前出现过，工作人员排查说Python进程处于Sl状态，检查发现，内核在等待62这个"文件"的数据。然后进一步查看，python进程fd下的62文件是一个socket连接，且这个连接没有/proc/net/tcp下，说明这个socket连接创建后，并没有被使用，所以Python一直卡死在“read（62，” 这个状态。
这次让log输出了图片名称，最后一次读的图片应该是正常图片。
任务号是trainjob-ddaa | jobd6683324

**Comment by chenliang613** [comment]
感谢您的反馈，此问题将按照华为云工单方式处理和解决。
