### ISSUE TITLE
ai course task1

### ISSUE THREAD

**Issue by Jasier** [huaweicloud/ModelArts-Lab#631]
华为云 AlexJ666
![1](https://user-images.githubusercontent.com/16295962/62606465-e3068400-b92e-11e9-9bc9-f4ccc42cba9f.png)
![2](https://user-images.githubusercontent.com/16295962/62606466-e3068400-b92e-11e9-9ac6-68d89c5a2b55.png)
![3](https://user-images.githubusercontent.com/16295962/62606467-e39f1a80-b92e-11e9-8214-ebaf69891f90.png)
![4](https://user-images.githubusercontent.com/16295962/62606470-e437b100-b92e-11e9-9ae8-ec7f7a93ffd3.png)

**Comment by JinhengZhang** [comment]
请在实战对应的issue后跟帖回复
