### ISSUE TITLE
第一期课程完成

### ISSUE THREAD

**Issue by yj196** [huaweicloud/ModelArts-Lab#636]
华为云账户： younge199
 
![image](https://user-images.githubusercontent.com/50231639/62679689-dc881300-b9e7-11e9-81f4-c8389b1d6214.png)
![image](https://user-images.githubusercontent.com/50231639/62682174-13612780-b9ee-11e9-8f4c-2c4187946038.png)

**Comment by JinhengZhang** [comment]
请在实战对应的issue后跟帖回复
