### ISSUE TITLE
华为云账号：whoamibyme

### ISSUE THREAD

**Issue by userkk** [huaweicloud/ModelArts-Lab#677]
自动学习案例截图：
![1](https://user-images.githubusercontent.com/32433624/62835759-a61ff180-bc8e-11e9-9a9c-02698d99e6a6.png)
![2](https://user-images.githubusercontent.com/32433624/62835764-ac15d280-bc8e-11e9-9710-5fa8399c3441.png)
![3](https://user-images.githubusercontent.com/32433624/62835766-addf9600-bc8e-11e9-8ce1-0be731ed19ce.png)
![4](https://user-images.githubusercontent.com/32433624/62835767-afa95980-bc8e-11e9-8606-e47d31e8e9f2.png)

**Comment by JinhengZhang** [comment]
你好，请在实践对应的issue后跟帖
