### ISSUE TITLE
aguicode-HuaweiLab1-ModelArts-Lab

### ISSUE THREAD

**Issue by PinkSmallFan** [huaweicloud/ModelArts-Lab#682]
华为云账号：aguicode
自动学习案例完成截图：

![AI-ExtML-flowers](https://user-images.githubusercontent.com/43728530/62837677-a1fece80-bca4-11e9-98bc-c62e0a0490c6.png)

**Comment by PinkSmallFan** [comment]
{
    "predicted_label": "菊花",
    "scores": [
        [
            "菊花",
            "0.756"
        ],
        [
            "玫瑰",
            "0.085"
        ],
        [
            "蒲公英",
            "0.081"
        ],
        [
            "向日葵",
            "0.079"
        ]
    ]
}

**Comment by JinhengZhang** [comment]
你好，请在实践对应的issue后跟帖回复
