### ISSUE TITLE
华为云账号：xgkh009

### ISSUE THREAD

**Issue by lcj1206** [huaweicloud/ModelArts-Lab#685]
华为云账号名：EasyArch_Yao
![QQ截图20190812220059](https://user-images.githubusercontent.com/47074991/62872734-ada7cf00-bd50-11e9-8842-029bc7330072.png)

![QQ截图20190812220123](https://user-images.githubusercontent.com/47074991/62872011-2b6adb00-bd4f-11e9-994c-183733cf7e57.png)
![QQ截图20190812220142](https://user-images.githubusercontent.com/47074991/62872014-2d349e80-bd4f-11e9-82e2-7892fbaade86.png)

notebook实验结果
![QQ截图20190812221708](https://user-images.githubusercontent.com/47074991/62872019-2dcd3500-bd4f-11e9-87c5-821f56a5c48d.png)

**Comment by lcj1206** [comment]
最新发现了两个坑！
官方文档的坑！！
在猫狗的notebook里面的环境搭建 给的是Python3 实际要用的是tensorflow环境 1.8 的可以！
1.13的报错有坑！
![39cdc755faa651901e04f641abae928](https://user-images.githubusercontent.com/47074991/62884815-06d02c80-bd6a-11e9-9f9b-38d4fa13f273.png)
![dbaef30d9d33e3c7e427830f2fd8c5b](https://user-images.githubusercontent.com/47074991/62884817-0768c300-bd6a-11e9-9149-b44e25a8202c.png)
![微信图片_20190813012956](https://user-images.githubusercontent.com/47074991/62884818-0768c300-bd6a-11e9-9eee-6637e9c3cae3.jpg)
![微信图片_20190813013001](https://user-images.githubusercontent.com/47074991/62884819-08015980-bd6a-11e9-9697-c20abc70d47f.jpg)
![微信图片_20190813013008](https://user-images.githubusercontent.com/47074991/62884822-08015980-bd6a-11e9-8cf0-58f01fc76d0d.jpg)

**Comment by chaoxu1203** [comment]
你好，第一期的案例完成结果请在issue #49下面反馈，否则无法获得积分哦。

**Comment by chaoxu1203** [comment]
截图里面的TF 1.13环境打印的日志，应该是warning，不是代码报错。
