### ISSUE TITLE
实验1

### ISSUE THREAD

**Issue by 1457695691** [huaweicloud/ModelArts-Lab#688]
华为云账号：EasyArch-Ayuan

自动学习案例完成截图：
![FireShot Capture 001 - 管理控制台-ModelArts - console huaweicloud com](https://user-images.githubusercontent.com/39644911/62882315-3845f980-bd64-11e9-9a44-291bcaef80d2.png)
![FireShot Capture 002 - 管理控制台-ModelArts - console huaweicloud com](https://user-images.githubusercontent.com/39644911/62882318-3845f980-bd64-11e9-8322-d23198aa3e1a.png)
![FireShot Capture 003 - 管理控制台-ModelArts - console huaweicloud com](https://user-images.githubusercontent.com/39644911/62882527-a5598f00-bd64-11e9-9bc9-87be5f85eb3b.png)
![FireShot Capture 004 - 管理控制台-ModelArts - console huaweicloud com](https://user-images.githubusercontent.com/39644911/62882324-38de9000-bd64-11e9-9c4d-a580f7b49370.png)
notebook完成截图:
![微信截图_20190812151248](https://user-images.githubusercontent.com/39644911/62882371-56abf500-bd64-11e9-94ac-e33c39633aba.png)

**Comment by chaoxu1203** [comment]
你好，每期案例请到对应的案例发布 issue 下面反馈实验结果，否则无法获得积分哦。
