### ISSUE TITLE
实验2

### ISSUE THREAD

**Issue by 1457695691** [huaweicloud/ModelArts-Lab#689]
华为云账号：EasyArch-Ayuan
![微信截图_20190813005533](https://user-images.githubusercontent.com/39644911/62882900-7ee82380-bd65-11e9-8559-c847648246f6.png)

![微信截图_20190813005726](https://user-images.githubusercontent.com/39644911/62882928-8b6c7c00-bd65-11e9-9473-7c83df2fb684.png)
![微信截图_20190813001756](https://user-images.githubusercontent.com/39644911/62882936-8e676c80-bd65-11e9-83a6-c89ebefd0409.png)
![微信截图_20190813003252](https://user-images.githubusercontent.com/39644911/62882947-91625d00-bd65-11e9-80eb-96521b6a7d5e.png)
![微信截图_20190813003308](https://user-images.githubusercontent.com/39644911/62882948-91625d00-bd65-11e9-9cbf-d24e62ad5766.png)
![微信截图_20190813003325](https://user-images.githubusercontent.com/39644911/62882949-91faf380-bd65-11e9-9344-823d7b69505d.png)
![微信截图_20190813003419](https://user-images.githubusercontent.com/39644911/62882951-92938a00-bd65-11e9-92e3-05e46bc71c11.png)

**Comment by chaoxu1203** [comment]
你好，每期案例请到对应的案例发布 issue 下面反馈实验结果，否则无法获得积分哦。
