### ISSUE TITLE
第四期

### ISSUE THREAD

**Issue by 1457695691** [huaweicloud/ModelArts-Lab#691]
华为云账号：EasyArch-Ayuan
notebookYOLO模型测试结果截图
![微信截图_20190813013637](https://user-images.githubusercontent.com/39644911/62890063-3b95b100-bd75-11e9-9192-14739d09a126.png)

预置部署YOLO模型测试结果截图
![微信截图_20190813024957](https://user-images.githubusercontent.com/39644911/62890095-4cdebd80-bd75-11e9-8758-9217f0b28fd5.png)

**Comment by chaoxu1203** [comment]
你好，每期案例请到对应的案例发布 issue 下面反馈实验结果，否则无法获得积分哦。
