### ISSUE TITLE
实战记录

### ISSUE THREAD

**Issue by 2531251963** [huaweicloud/ModelArts-Lab#702]
华为云账号：xgkh0014
自动学习案例完成截图：
![屏幕截图 2019-08-13 18:48:28](https://user-images.githubusercontent.com/40883558/62937376-05047880-bdff-11e9-907a-4856892f35ca.png)
![屏幕截图 2019-08-13 18:49:36](https://user-images.githubusercontent.com/40883558/62937393-13529480-bdff-11e9-8abd-cda1bd0b53df.png)
![屏幕截图 2019-08-13 18:50:10](https://user-images.githubusercontent.com/40883558/62937397-15b4ee80-bdff-11e9-9648-0a5a2b0a3214.png)
![屏幕截图 2019-08-13 18:50:23](https://user-images.githubusercontent.com/40883558/62937402-177eb200-bdff-11e9-825a-e3e0146d570c.png)
Notebook案例完成截图：
![屏幕截图 2019-08-13 19:13:26](https://user-images.githubusercontent.com/40883558/62937419-26fdfb00-bdff-11e9-9711-c8c88c3232c8.png)

**Comment by JinhengZhang** [comment]
你好，第一期的案例完成结果请在issue #49 下面跟帖反馈
