### ISSUE TITLE
华为云账号：EasyArch-Ayuan

### ISSUE THREAD

**Issue by 1457695691** [huaweicloud/ModelArts-Lab#714]
华为云账号：EasyArch-Ayuan
notebook模型运行结果截图:
![微信截图_20190813022948](https://user-images.githubusercontent.com/39644911/62914761-43c90d00-bdc4-11e9-8975-4ceb9ecef5c5.png)
![微信截图_20190813023013](https://user-images.githubusercontent.com/39644911/62914762-4461a380-bdc4-11e9-9178-e0b3ca0d925c.png)

预置模型运行结果截图:
![微信截图_20190813121909](https://user-images.githubusercontent.com/39644911/62914831-9c98a580-bdc4-11e9-8f27-b00c0323c4d3.png)
在线服务测试结果：
![微信截图_20190813053518](https://user-images.githubusercontent.com/39644911/62914858-ab7f5800-bdc4-11e9-81fe-463280b8d456.png)

_Originally posted by @1457695691 in https://github.com/huaweicloud/ModelArts-Lab/issues/637#issuecomment-520682729_

**Comment by chaoxu1203** [comment]
你好，第五期的实验结果请在第五期的issue下反馈哈，否则无法获得积分。
