### ISSUE TITLE
搭建数字识别在线服务及完整的验证码的识别应用代码

### ISSUE THREAD

**Issue by wonleing** [huaweicloud/ModelArts-Lab#8]
详情查看
https://github.com/wonleing/AI_number_recognize/wiki
里面有搭建模型训练及在线服务的跳坑指南，以及完整的网站验证码识别应用。（ubuntu python2.7下运行）

**Comment by chenliang613** [comment]
Thanks for sharing.
Two comments:
1.更准确的描述是：华为云ModelArts AI开发平台，不是AI引擎（如TensorFlow）
---------------------------------------------------------------- 
华为云AI引擎训练手写数字识别后的一个完整应用案例

2.能否请将此案例贡献到社区？  创建一个“contrib”文件夹，把你这个案例往里面放。

**Comment by wonleing** [comment]
放在github   ModelArts-Lab/综合AI开发案例/MNIST Dataset Recognition/  里吗？我没有这里的写入权限。

**Comment by chenliang613** [comment]
你这个总结，整体放在contrib目录下。

**Comment by wonleing** [comment]
应用案例及代码贡献 #13
wonleing wants to merge 4 commits into huaweicloud:master from wonleing:master

**Comment by chenliang613** [comment]
PR already be merged, close this issue.
