### ISSUE TITLE
华为账号：wuyicom

### ISSUE THREAD

**Issue by wuyi1405** [huaweicloud/ModelArts-Lab#827]
华为账号：wuyicom

自动学习案例完成截图：

_Originally posted by @wuyi1405 in https://github.com/huaweicloud/ModelArts-Lab/issues/49#issuecomment-524204923_
!GitHub的标志)(/图片/ logo.png)
Format: !(Alt文本)(url)

**Comment by chaoxu1203** [comment]
你好，第一期的完成结果，请在issue #49 下面反馈哦
