### ISSUE TITLE
训练作业一直卡在部署中。。。。

### ISSUE THREAD

**Issue by longWC** [huaweicloud/ModelArts-Lab#917]
训练作业一直卡在部署中，也不给一点提示？是因为资源不够吗？反正使用起来总是差一口气

**Comment by chaoxu1203** [comment]
你好，这是在排队中。由于使用的是公共资源池，所以在使用高峰期资源不足的时候，会有排队现象。后面我们会优化提示信息。

**Comment by GitLD** [comment]
你应该是用了4*P100换成单个P100应该就可以，我之前4*P100卡了3-4个小时，单个P100基本上没有部署时间，虽然训练上4*P100比较快

**Comment by longWC** [comment]
嗯嗯，应该是4*p100资源比较紧张的缘故，挂着第二天就跑好了
