### ISSUE TITLE
第一期

### ISSUE THREAD

**Issue by Toin1779712664** [huaweicloud/ModelArts-Lab#943]
华为云账号：Toinaa
自动学习案例完成截图：
![WeChat39797e6e93f40f090dc6d8d57b50dffb](https://user-images.githubusercontent.com/31212492/64579406-63e4ef80-d3b5-11e9-9767-b0f4e73d8c85.png)

**Comment by chaoxu1203** [comment]
请到第一期的 issue #49 下面反馈实践结果，否则无法获得积分哦
