### ISSUE TITLE
华为云ModelArts-Lab AI实战营】第一期：图像分类 (I)

### ISSUE THREAD

**Issue by lixixue** [huaweicloud/ModelArts-Lab#948]
华为云账号：hw00515751
![image](https://user-images.githubusercontent.com/16068979/64593953-a4f2f900-d3e1-11e9-9f02-7468c5e6f615.png)
![image](https://user-images.githubusercontent.com/16068979/64593998-bd631380-d3e1-11e9-947f-3faadae3cdb9.png)

**Comment by JinhengZhang** [comment]
@lixixue 请在第一期实战issue后跟帖反馈，谢谢！
